In [1]:
import json
import pandas as pd
from pathlib import Path

In [2]:
pwd

'/Users/thomasjoseph/Desktop/JMJTL/Projects/Gen_ai/GEO'

In [3]:
path = "/Users/thomasjoseph/Desktop/JMJTL/Projects/Gen_ai/GEO/geo_discovery/geo_projects/danone/aptamil/audit_raw.jsonl"

In [4]:
rows = [json.loads(l) for l in open(path, encoding="utf-8")]
df = pd.DataFrame([r for r in rows if r.get("success")])

In [5]:
df.shape

(620, 19)

In [6]:
df.head()

,query,engine,model,web_on,run_index,timestamp,success,response_text,sources,num_sources,source_type_tally,image_urls,num_images,web_search_queries,image_insights,brand_mentions,outcome,classification,intent
0,Is Aptamil's Pronutra formulation effective fo...,gemini-2.5-flash,gemini-2.5-flash,True,0,2026-09-02T06:48:58.665526+00:00,True,Aptamil's Pronutra formulation is designed to ...,"[{'title': 'euromallusa.com', 'url': 'https://...",5,"{'other': 4, 'video_social': 1}","[[], [https://www.youtube.com/watch?v=hJczNuX5...",2,[Aptamil Pronutra formulation effectiveness in...,"[{'url': [], 'fetched': False}, {'url': ['http...","{'aptamil': {'mentioned': True, 'first_index':...",partial,"{'outcome': 'partial', 'refusal_reason': 'none...",branded
1,Is Aptamil's Pronutra formulation effective fo...,gemini-2.5-flash,gemini-2.5-flash,True,1,2026-09-02T06:49:12.309015+00:00,True,Aptamil's Pronutra formulation is designed to ...,"[{'title': 'euromallusa.com', 'url': 'https://...",10,"{'other': 8, 'video_social': 2}","[[], [https://www.youtube.com/watch?v=tyaqo_fX...",2,[Aptamil Pronutra formulation effectiveness in...,"[{'url': [], 'fetched': False}, {'url': ['http...","{'aptamil': {'mentioned': True, 'first_index':...",partial,"{'outcome': 'partial', 'refusal_reason': 'none...",branded
2,Is Aptamil's Pronutra formulation effective fo...,gemini-2.5-flash,gemini-2.5-flash,True,2,2026-09-02T06:49:26.736799+00:00,True,Aptamil's Pronutra formulation is designed to ...,"[{'title': 'bonpek.com', 'url': 'https://verte...",7,"{'other': 6, 'video_social': 1}","[[], [https://www.youtube.com/watch?v=hJczNuX5...",2,[Aptamil Pronutra infant development effective...,"[{'url': [], 'fetched': False}, {'url': ['http...","{'aptamil': {'mentioned': True, 'first_index':...",brand_recommended,"{'outcome': 'brand_recommended', 'refusal_reas...",branded
3,Is Aptamil's Pronutra formulation effective fo...,gemini-2.5-flash,gemini-2.5-flash,True,3,2026-09-02T06:49:53.010825+00:00,True,Aptamil's Pronutra formulation is designed to ...,"[{'title': 'nutraingredients.com', 'url': 'htt...",15,"{'other': 14, 'video_social': 1}","[[], [https://www.youtube.com/watch?v=hJczNuX5...",2,[Aptamil Pronutra infant development effective...,"[{'url': [], 'fetched': False}, {'url': ['http...","{'aptamil': {'mentioned': True, 'first_index':...",brand_recommended,"{'outcome': 'brand_recommended', 'refusal_reas...",branded
4,Is Aptamil's Pronutra formulation effective fo...,gemini-2.5-flash,gemini-2.5-flash,True,4,2026-09-02T06:50:06.960163+00:00,True,Aptamil's Pronutra formulation is designed to ...,"[{'title': 'euromallusa.com', 'url': 'https://...",9,"{'other': 8, 'video_social': 1}","[[], [https://www.youtube.com/watch?v=hJczNuX5...",2,[Aptamil Pronutra effectiveness infant develop...,"[{'url': [], 'fetched': False}, {'url': ['http...","{'aptamil': {'mentioned': True, 'first_index':...",partial,"{'outcome': 'partial', 'refusal_reason': 'none...",branded

In [11]:
def _is_first(row, target):
    bm = row.get("brand_mentions", {}) or {}
    present = [(b, v.get("first_index", -1)) for b, v in bm.items()
               if v.get("first_index", -1) >= 0]
    if not present: return False
    return min(present, key=lambda x: x[1])[0] == target

In [12]:
target_brand = "aptamil"
df["mentioned"] = df["brand_mentions"].apply(
        lambda b: b.get(target_brand, {}).get("mentioned", False))
df["first_index"] = df["brand_mentions"].apply(
        lambda b: b.get(target_brand, {}).get("first_index", -1))
df["is_first"] = df.apply(lambda r: _is_first(r, target_brand), axis=1)
df["refusal"] = df["outcome"] == "refusal"
df["sentiment"] = df["classification"].apply(
    lambda c: (c or {}).get("sentiment_toward_target") if isinstance(c, dict) else None)

In [14]:
df.head()

,query,engine,model,web_on,run_index,timestamp,success,response_text,sources,num_sources,...,image_insights,brand_mentions,outcome,classification,intent,mentioned,first_index,is_first,refusal,sentiment
0,Is Aptamil's Pronutra formulation effective fo...,gemini-2.5-flash,gemini-2.5-flash,True,0,2026-09-02T06:48:58.665526+00:00,True,Aptamil's Pronutra formulation is designed to ...,"[{'title': 'euromallusa.com', 'url': 'https://...",5,...,"[{'url': [], 'fetched': False}, {'url': ['http...","{'aptamil': {'mentioned': True, 'first_index':...",partial,"{'outcome': 'partial', 'refusal_reason': 'none...",branded,True,0,True,False,positive
1,Is Aptamil's Pronutra formulation effective fo...,gemini-2.5-flash,gemini-2.5-flash,True,1,2026-09-02T06:49:12.309015+00:00,True,Aptamil's Pronutra formulation is designed to ...,"[{'title': 'euromallusa.com', 'url': 'https://...",10,...,"[{'url': [], 'fetched': False}, {'url': ['http...","{'aptamil': {'mentioned': True, 'first_index':...",partial,"{'outcome': 'partial', 'refusal_reason': 'none...",branded,True,0,True,False,positive
2,Is Aptamil's Pronutra formulation effective fo...,gemini-2.5-flash,gemini-2.5-flash,True,2,2026-09-02T06:49:26.736799+00:00,True,Aptamil's Pronutra formulation is designed to ...,"[{'title': 'bonpek.com', 'url': 'https://verte...",7,...,"[{'url': [], 'fetched': False}, {'url': ['http...","{'aptamil': {'mentioned': True, 'first_index':...",brand_recommended,"{'outcome': 'brand_recommended', 'refusal_reas...",branded,True,0,True,False,positive
3,Is Aptamil's Pronutra formulation effective fo...,gemini-2.5-flash,gemini-2.5-flash,True,3,2026-09-02T06:49:53.010825+00:00,True,Aptamil's Pronutra formulation is designed to ...,"[{'title': 'nutraingredients.com', 'url': 'htt...",15,...,"[{'url': [], 'fetched': False}, {'url': ['http...","{'aptamil': {'mentioned': True, 'first_index':...",brand_recommended,"{'outcome': 'brand_recommended', 'refusal_reas...",branded,True,0,True,False,positive
4,Is Aptamil's Pronutra formulation effective fo...,gemini-2.5-flash,gemini-2.5-flash,True,4,2026-09-02T06:50:06.960163+00:00,True,Aptamil's Pronutra formulation is designed to ...,"[{'title': 'euromallusa.com', 'url': 'https://...",9,...,"[{'url': [], 'fetched': False}, {'url': ['http...","{'aptamil': {'mentioned': True, 'first_index':...",partial,"{'outcome': 'partial', 'refusal_reason': 'none...",branded,True,0,True,False,positive

In [16]:
df.columns

Index(['query', 'engine', 'model', 'web_on', 'run_index', 'timestamp',
       'success', 'response_text', 'sources', 'num_sources',
       'source_type_tally', 'image_urls', 'num_images', 'web_search_queries',
       'image_insights', 'brand_mentions', 'outcome', 'classification',
       'intent', 'mentioned', 'first_index', 'is_first', 'refusal',
       'sentiment'],
      dtype='object')

In [15]:
g = df.groupby(["engine", "intent"])["mentioned"].agg(hits="sum", runs="count").reset_index()
g

             engine       intent  hits  runs
0      azure/gpt-4o      branded    30    30
1      azure/gpt-4o  comparative    30    30
2      azure/gpt-4o         need     0   170
3      azure/gpt-4o     negative     0    50
4      azure/gpt-4o      persona     0    20
5  gemini-2.5-flash      branded    30    30
6  gemini-2.5-flash  comparative    30    30
7  gemini-2.5-flash         need    16   190
8  gemini-2.5-flash     negative     0    50
9  gemini-2.5-flash      persona     0    20

In [17]:
def _first_brand(bm):
    present = [(b, v.get("first_index",-1)) for b,v in (bm or {}).items()
               if v.get("first_index",-1) >= 0]
    return min(present, key=lambda x:x[1])[0] if present else None

In [25]:
b = "SMA"
first = df["brand_mentions"].apply(
            lambda bm: _first_brand(bm) == b).sum()
first

np.int64(128)

In [21]:
df.brand_mentions[0]

{'aptamil': {'mentioned': True, 'first_index': 0},
 'Kendamil': {'mentioned': False, 'first_index': -1},
 'HiPP Organic': {'mentioned': False, 'first_index': -1},
 'Cow & Gate': {'mentioned': False, 'first_index': -1},
 'SMA': {'mentioned': False, 'first_index': -1},
 'Enfamil': {'mentioned': False, 'first_index': -1},
 'Similac': {'mentioned': False, 'first_index': -1},
 'Aldi Mamia': {'mentioned': False, 'first_index': -1},
 'Kirkland Signature ProCare': {'mentioned': False, 'first_index': -1},
 'Bobbie Organic': {'mentioned': False, 'first_index': -1},
 'Holle Cow': {'mentioned': False, 'first_index': -1}}

In [31]:
for eng, g in df.groupby("engine"):
    for tally in g["source_type_tally"]:
        print(tally)
        print("############")

{'other': 3}
############
{'other': 2}
############
{'other': 4}
############
{'other': 2}
############
{'other': 2}
############
{'other': 4}
############
{'other': 2}
############
{'other': 3}
############
{'other': 3}
############
{'other': 3}
############
{}
############
{'other': 2}
############
{'other': 4}
############
{'other': 3}
############
{'other': 2}
############
{'other': 4}
############
{'other': 2}
############
{'other': 5}
############
{}
############
{}
############
{'other': 4}
############
{'other': 4}
############
{'other': 4}
############
{'other': 4}
############
{'other': 3}
############
{'other': 4}
############
{'other': 4}
############
{'other': 4}
############
{'other': 4}
############
{'other': 4}
############
{'other': 3}
############
{'other': 4}
############
{'other': 4}
############
{'other': 3}
############
{'other': 3}
############
{'other': 5}
############
{'other': 4}
############
{'other': 4}
############
{'other': 3}
############
{'other': 4}
############
{'other': 3}
############
{'other': 3}
############
{'other': 3}
############
{'other': 4}
############
{'other': 3}
############
{'other': 3}
############
{'other': 3}
############
{'other': 4}
############
{'other': 3}
############
{'other': 4}
############
{'other': 6}
############
{'other': 6}
############
{'other': 6}
############
{'other': 5}
############
{'other': 5}
############
{'other': 6}
############
{'other': 6}
############
{'other': 6}
############
{'other': 5}
############
{'other': 5}
############
{'other': 3}
############
{'other': 4}
############
{'other': 3}
############
{'other': 3}
############
{'other': 5}
############
{'other': 4}
############
{'other': 4}
############
{'other': 4}
############
{'other': 4}
############
{'other': 5}
############
{'other': 5}
############
{'other': 5}
############
{'other': 4}
############
{'other': 4}
############
{'other': 4}
############
{'other': 4}
############
{'other': 3}
############
{'other': 5}
############
{'other': 3}
############
{'other': 5}
############
{'other': 4}
############
{'other': 4}
############
{'other': 4}
############
{'other': 4}
############
{'other': 4}
############
{'other': 5}
############
{'other': 5}
############
{'other': 5}
############
{'other': 5}
############
{'other': 4}
############
{'other': 5}
############
{'other': 5}
############
{'other': 5}
############
{'other': 5}
############
{'other': 5}
############
{'other': 5}
############
{'other': 3}
############
{'other': 5}
############
{'other': 5}
############
{'other': 6}
############
{'other': 5}
############
{'other': 4}
############
{'other': 6}
############
{'other': 4}
############
{'other': 6}
############
{'other': 4}
############
{'other': 2}
############
{'other': 5}
############
{'other': 4}
############
{'other': 4}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{'other': 4}
############
{'other': 5}
############
{'other': 5}
############
{'other': 5}
############
{'other': 4}
############
{'other': 5}
############
{'other': 4}
############
{'other': 4}
############
{'other': 6}
############
{'other': 4}
############
{'other': 4}
############
{'other': 4}
############
{'other': 4}
############
{'other': 5}
############
{'other': 3}
############
{'other': 4}
############
{'other': 3}
############
{'other': 2}
############
{'other': 3}
############
{'other': 5}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{'other': 5}
############
{'other': 4}
############
{'other': 4}
############
{'other': 5}
############
{'other': 6}
############
{'other': 4}
############
{'other': 5}
############
{'other': 4}
############
{'other': 5}
############
{'other': 3}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{'other': 6}
############
{'other': 5}
############
{'other': 4}
############
{'other': 5}
############
{'other': 4}
############
{'other': 3}
############
{'other': 5}
############
{'other': 6}
############
{'other': 3}
############
{'other': 3}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{'other': 5}
############
{'other': 5}
############
{'other': 5}
############
{'other': 6}
############
{'other': 5}
############
{'other': 7}
############
{'other': 5}
############
{'other': 4}
############
{'other': 5}
############
{'other': 5}
############
{}
############
{}
############
{}
############
{'other': 2}
############
{'other': 2}
############
{'other': 6}
############
{}
############
{'other': 4}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{'other': 4}
############
{'other': 3}
############
{'other': 5}
############
{'other': 3}
############
{'other': 4}
############
{'other': 4}
############
{'other': 4}
############
{'other': 4}
############
{'other': 4}
############
{'other': 2}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{}
############
{'other': 4, 'video_social': 1}
############
{'other': 8, 'video_social': 2}
############
{'other': 6, 'video_social': 1}
############
{'other': 14, 'video_social': 1}
############
{'other': 8, 'video_social': 1}
############
{'other': 10, 'video_social': 1}
############
{'other': 22, 'video_social': 1, 'editorial_authority': 4, 'community_reviews': 1}
############
{'other': 6, 'video_social': 1}
############
{'other': 8, 'video_social': 2}
############
{'other': 11, 'video_social': 1}
############
{'other': 19, 'editorial_authority': 1}
############
{'other': 18, 'editorial_authority': 1}
############
{'other': 6, 'video_social': 2}
############
{'other': 7}
############
{'other': 9}
############
{'other': 10}
############
{'other': 11}
############
{'other': 6}
############
{'other': 14, 'editorial_authority': 1}
############
{'other': 10, 'editorial_authority': 1}
############
{'other': 6, 'video_social': 1}
############
{'other': 9, 'video_social': 1}
############
{'other': 9, 'video_social': 1}
############
{'other': 8, 'video_social': 1}
############
{'other': 8, 'community_reviews': 1, 'video_social': 1}
############
{'other': 7, 'community_reviews': 1, 'video_social': 2}
############
{'other': 7, 'video_social': 1}
############
{'other': 7, 'video_social': 1}
############
{'other': 7, 'video_social': 1}
############
{'other': 7, 'video_social': 1}
############
{'other': 14, 'retailer': 1}
############
{'other': 13, 'community_reviews': 1, 'video_social': 1}
############
{'other': 13, 'community_reviews': 1, 'retailer': 1}
############
{'community_reviews': 1, 'other': 23, 'retailer': 1}
############
{'community_reviews': 1, 'other': 12, 'video_social': 1}
############
{'community_reviews': 1, 'other': 14, 'retailer': 1}
############
{'other': 12, 'retailer': 1}
############
{'community_reviews': 1, 'other': 12}
############
{'other': 12, 'retailer': 1, 'video_social': 1}
############
{'other': 15, 'retailer': 1}
############
{'other': 19}
############
{'other': 16}
############
{'other': 18}
############
{'other': 14, 'community_reviews': 1}
############
{'other': 20}
############
{'other': 10}
############
{'other': 11}
############
{'other': 12, 'editorial_authority': 1}
############
{'other': 13, 'editorial_authority': 1}
############
{'other': 19, 'editorial_authority': 1}
############
{'other': 20, 'video_social': 1}
############
{'other': 20}
############
{'other': 20, 'retailer': 1}
############
{'other': 13}
############
{'other': 12}
############
{'other': 15}
############
{'other': 13}
############
{'other': 18}
############
{'other': 12}
############
{'other': 11, 'video_social': 1}
############
{'other': 9}
############
{'other': 4, 'video_social': 1, 'retailer': 1}
############
{'other': 20, 'editorial_authority': 2, 'retailer': 1}
############
{'other': 5, 'retailer': 1}
############
{'other': 6, 'video_social': 1, 'retailer': 1}
############
{'other': 14, 'editorial_authority': 1}
############
{'other': 16, 'video_social': 1, 'retailer': 1}
############
{'other': 14, 'editorial_authority': 1}
############
{'other': 15, 'editorial_authority': 1}
############
{'other': 10}
############
{'other': 5, 'video_social': 1}
############
{'other': 22, 'retailer': 2}
############
{'other': 9, 'retailer': 1}
############
{'other': 9}
############
{'other': 4, 'community_reviews': 1, 'video_social': 1, 'retailer': 1}
############
{'other': 12, 'editorial_authority': 1, 'video_social': 1}
############
{'other': 7, 'community_reviews': 1}
############
{'other': 6, 'video_social': 1, 'retailer': 1}
############
{'other': 20, 'editorial_authority': 1, 'retailer': 1, 'video_social': 1, 'brand_owned': 1}
############
{'other': 8, 'video_social': 1}
############
{'other': 16, 'editorial_authority': 4, 'community_reviews': 1}
############
{'other': 15, 'editorial_authority': 3, 'brand_owned': 1}
############
{'other': 8, 'editorial_authority': 1, 'retailer': 1}
############
{'editorial_authority': 3, 'other': 13}
############
{'other': 14, 'editorial_authority': 2}
############
{'other': 17, 'editorial_authority': 2}
############
{'other': 6, 'editorial_authority': 1}
############
{'editorial_authority': 2, 'other': 10}
############
{'other': 16, 'editorial_authority': 2}
############
{'other': 15, 'editorial_authority': 2}
############
{'other': 13}
############
{'community_reviews': 1, 'other': 10, 'video_social': 1}
############
{'other': 7}
############
{'other': 9, 'community_reviews': 1}
############
{'other': 26}
############
{'other': 6}
############
{'other': 12, 'editorial_authority': 1}
############
{'other': 14, 'editorial_authority': 2}
############
{'other': 5}
############
{'other': 11}
############
{'community_reviews': 1, 'other': 16, 'editorial_authority': 1, 'retailer': 3}
############
{'other': 23, 'editorial_authority': 1}
############
{'other': 17}
############
{'other': 24, 'editorial_authority': 2, 'retailer': 2}
############
{'other': 23, 'editorial_authority': 3, 'retailer': 3}
############
{'other': 17, 'editorial_authority': 2, 'retailer': 3}
############
{'other': 21, 'retailer': 2}
############
{'other': 9}
############
{'other': 20, 'editorial_authority': 1, 'retailer': 3}
############
{'other': 17, 'editorial_authority': 3, 'retailer': 4}
############
{'other': 10}
############
{'other': 6}
############
{'other': 11}
############
{'other': 6, 'community_reviews': 1}
############
{'other': 8}
############
{'other': 18}
############
{'other': 6}
############
{'other': 17, 'editorial_authority': 1}
############
{'other': 17, 'editorial_authority': 2}
############
{'other': 17, 'community_reviews': 1, 'editorial_authority': 1}
############
{'other': 11, 'editorial_authority': 2}
############
{'other': 6, 'editorial_authority': 2}
############
{'other': 7, 'editorial_authority': 2}
############
{'other': 11, 'editorial_authority': 2, 'video_social': 1}
############
{'other': 11, 'editorial_authority': 4, 'video_social': 2}
############
{'other': 8, 'editorial_authority': 3}
############
{'other': 11, 'editorial_authority': 2}
############
{'other': 9, 'editorial_authority': 3}
############
{'other': 10, 'editorial_authority': 1}
############
{'other': 8, 'editorial_authority': 2}
############
{'other': 17, 'editorial_authority': 1, 'community_reviews': 1}
############
{'other': 22, 'editorial_authority': 1}
############
{'other': 9, 'editorial_authority': 1}
############
{'other': 8, 'editorial_authority': 1}
############
{'other': 8, 'editorial_authority': 1}
############
{'community_reviews': 1, 'other': 21, 'editorial_authority': 2}
############
{'other': 25, 'editorial_authority': 1, 'community_reviews': 1, 'retailer': 1}
############
{'other': 16, 'editorial_authority': 2}
############
{'other': 21, 'editorial_authority': 3}
############
{'other': 23, 'editorial_authority': 1, 'community_reviews': 1, 'retailer': 1}
############
{'community_reviews': 1, 'other': 2, 'retailer': 1, 'video_social': 1}
############
{'other': 4, 'video_social': 1}
############
{'other': 6, 'video_social': 1, 'retailer': 1}
############
{'other': 8, 'video_social': 1}
############
{'other': 13, 'brand_owned': 2, 'editorial_authority': 3, 'retailer': 1, 'video_social': 1}
############
{'other': 15, 'community_reviews': 2, 'video_social': 1}
############
{'other': 13, 'video_social': 1}
############
{'other': 5, 'retailer': 2, 'video_social': 1}
############
{'other': 5, 'video_social': 1}
############
{'other': 19, 'brand_owned': 1}
############
{'other': 12, 'video_social': 1, 'retailer': 1}
############
{'other': 6, 'retailer': 1, 'video_social': 1}
############
{'other': 6, 'community_reviews': 1, 'retailer': 1, 'video_social': 1}
############
{'other': 5, 'video_social': 1}
############
{'community_reviews': 1, 'other': 6, 'retailer': 1, 'video_social': 1}
############
{'other': 6, 'video_social': 1}
############
{'other': 8, 'video_social': 1}
############
{'video_social': 1, 'other': 1}
############
{'other': 16, 'retailer': 3, 'video_social': 1}
############
{'other': 7, 'video_social': 1, 'retailer': 1}
############
{'other': 10}
############
{'other': 10}
############
{'other': 9}
############
{'other': 6, 'editorial_authority': 1}
############
{'other': 11}
############
{'other': 7, 'editorial_authority': 2}
############
{'editorial_authority': 1, 'other': 13}
############
{'editorial_authority': 2, 'other': 11}
############
{'other': 10, 'editorial_authority': 1}
############
{'other': 13, 'editorial_authority': 2}
############
{'other': 7}
############
{'other': 8}
############
{'other': 8}
############
{'other': 18, 'retailer': 1}
############
{'other': 8}
############
{'other': 13, 'retailer': 1}
############
{'other': 5}
############
{'other': 11, 'retailer': 1}
############
{'other': 12}
############
{'other': 8}
############
{'other': 13, 'editorial_authority': 1, 'retailer': 1}
############
{'other': 7}
############
{'brand_owned': 1, 'other': 16}
############
{'other': 4}
############
{'other': 6}
############
{'other': 6}
############
{'other': 6}
############
{'other': 8}
############
{'other': 7}
############
{'other': 8}
############
{'other': 9, 'editorial_authority': 1}
############
{'other': 9, 'editorial_authority': 1}
############
{'other': 12, 'editorial_authority': 2}
############
{'other': 9, 'editorial_authority': 1}
############
{'other': 16, 'editorial_authority': 2, 'retailer': 1}
############
{'other': 11, 'editorial_authority': 1}
############
{'retailer': 2, 'other': 9, 'editorial_authority': 2}
############
{'other': 12, 'retailer': 2, 'editorial_authority': 2}
############
{'other': 11, 'editorial_authority': 1}
############
{'other': 10, 'editorial_authority': 2, 'retailer': 2}
############
{'editorial_authority': 2, 'other': 14}
############
{'other': 10, 'brand_owned': 1, 'editorial_authority': 1}
############
{'other': 11, 'editorial_authority': 2}
############
{'other': 9, 'editorial_authority': 2}
############
{'other': 11, 'editorial_authority': 3}
############
{'other': 10, 'editorial_authority': 2, 'retailer': 1}
############
{'other': 10, 'editorial_authority': 2}
############
{'other': 10, 'editorial_authority': 1}
############
{'other': 10, 'editorial_authority': 3}
############
{'other': 9, 'editorial_authority': 3}
############
{'community_reviews': 1, 'other': 7}
############
{'community_reviews': 1, 'other': 8}
############
{'other': 6, 'community_reviews': 1}
############
{'community_reviews': 1, 'other': 9}
############
{'other': 9, 'community_reviews': 1}
############
{'other': 7, 'community_reviews': 1}
############
{'other': 6, 'community_reviews': 1}
############
{'community_reviews': 1, 'other': 6}
############
{'other': 6, 'community_reviews': 1}
############
{'other': 6, 'community_reviews': 1}
############
{'community_reviews': 1, 'other': 12}
############
{'other': 12, 'community_reviews': 1, 'editorial_authority': 1}
############
{'other': 12, 'community_reviews': 1}
############
{'other': 10, 'community_reviews': 1}
############
{'other': 15, 'community_reviews': 1, 'editorial_authority': 1}
############
{'other': 11, 'community_reviews': 1}
############
{'other': 14, 'community_reviews': 1}
############
{'community_reviews': 2, 'other': 6}
############
{'other': 13, 'community_reviews': 1}
############
{'community_reviews': 1, 'other': 7}
############
{'other': 19}
############
{'other': 2, 'community_reviews': 1}
############
{'other': 6, 'retailer': 1}
############
{'other': 9, 'retailer': 2}
############
{'other': 16, 'community_reviews': 1}
############
{'other': 4, 'community_reviews': 1, 'retailer': 1}
############
{'other': 5}
############
{'other': 5}
############
{'other': 4, 'retailer': 2}
############
{'other': 13}
############
{'other': 7, 'retailer': 1, 'editorial_authority': 1}
############
{'other': 6, 'editorial_authority': 1}
############
{'other': 7}
############
{'other': 6, 'editorial_authority': 1}
############
{'other': 5, 'retailer': 1, 'editorial_authority': 1}
############
{'other': 6, 'retailer': 1, 'editorial_authority': 1}
############
{'other': 7, 'editorial_authority': 1}
############
{'other': 3, 'retailer': 1, 'editorial_authority': 1}
############
{'other': 6, 'editorial_authority': 1}
############
{'other': 6, 'editorial_authority': 1}
############
{'other': 8}
############
{'other': 8}
############
{'other': 12, 'community_reviews': 1}
############
{'other': 15}
############
{'other': 14}
############
{'other': 14, 'community_reviews': 1}
############
{'other': 10}
############
{'other': 9}
############
{'community_reviews': 1, 'other': 14}
############
{'other': 10, 'community_reviews': 1}
############
{'other': 9}
############
{'other': 9}
############
{'other': 9, 'editorial_authority': 1}
############
{'other': 15}
############
{'other': 12, 'editorial_authority': 1}
############
{'other': 10}
############
{'other': 11, 'editorial_authority': 2}
############
{'other': 16, 'editorial_authority': 1}
############
{'other': 11}
############
{'other': 16}
############
{'other': 11, 'editorial_authority': 1}
############
{'other': 10, 'editorial_authority': 1}
############
{'other': 13, 'editorial_authority': 1}
############
{'other': 7}
############
{'other': 9, 'editorial_authority': 1}
############
{'editorial_authority': 1, 'other': 9}
############
{'other': 9, 'editorial_authority': 1}
############
{'other': 10, 'editorial_authority': 1}
############
{'other': 7, 'editorial_authority': 1}
############

In [32]:
g["source_type_tally"]

0              {'other': 4, 'video_social': 1}
1              {'other': 8, 'video_social': 2}
2              {'other': 6, 'video_social': 1}
3             {'other': 14, 'video_social': 1}
4              {'other': 8, 'video_social': 1}
                        ...
605                              {'other': 12}
606                              {'other': 16}
607                              {'other': 11}
608    {'other': 17, 'editorial_authority': 1}
609    {'other': 16, 'editorial_authority': 1}
Name: source_type_tally, Length: 320, dtype: object

In [37]:
sample = "\n---\n".join(df["response_text"].tolist())
sample

'Aptamil\'s Pronutra formulation is designed to support infant development by providing a blend of nutrients intended to mimic the nutritional profile of breast milk. It incorporates a scientifically formulated mix of ingredients aimed at bolstering various aspects of a baby\'s growth and health.\n\nKey components and their intended benefits for infant development include:\n*   **Essential Fatty Acids (DHA and ARA/LCPs)**: These are crucial for cognitive and visual development, playing a significant role in brain and eye health.\n*   **Prebiotics (GOS/FOS blend)**: Aptamil Pronutra contains a patented blend of galacto-oligosaccharides (GOS) and fructo-oligosaccharides (FOS) which are prebiotics. These are intended to support healthy gut bacteria, digestive health, and a robust immune system.\n*   **Vitamins and Minerals**: The formulation is enriched with vitamins A, C, and D, as well as iron and other essential nutrients. Vitamins A, C, and D are vital for immune system support, while iron contributes to normal cognitive development. Vitamin D and calcium also support bone development.\n*   **Other Nutrients**: Ingredients like taurine and L-carnitine are also included to support optimal health and development.\n\nAptamil Pronutra aims to provide comprehensive nutrition, supporting healthy growth, digestion, immune function, and brain development during critical stages of infancy. The brand emphasizes its commitment to infant nutrition and scientific research, with formulations evolving based on advancements in nutritional science. It is also noted that European formulas like Aptamil often avoid ingredients such as corn syrup solids and artificial preservatives, which some parents prefer to limit.\n\nWhile Aptamil Pronutra is developed to provide essential nutrients for infant development, it is important to note that breast milk is widely recognized as the best source of nutrition for babies, offering a perfectly balanced composition and a stronger immune system. Infant formulas like Aptamil are often used when breastfeeding is not possible or as a supplement, and their use is recommended to be on the advice of a doctor.\n---\nAptamil\'s Pronutra formulation is designed to support infant development through a blend of specific nutrients, often mirroring components found in breast milk. This formulation is based on extensive research and aims to cater to the nutritional needs of babies at various stages of growth.\n\nKey components of Aptamil Pronutra and their purported benefits for infant development include:\n*   **Prebiotics (GOS/FOS blend)**: These patented prebiotics are intended to support healthy gut bacteria, promote healthy digestion, and contribute to a gut microbiota closer to that of breastfed babies. Some parents have reported improved digestion and reduced issues like gas and constipation with formulas containing these blends.\n*   **LCPs (Long-Chain Polyunsaturated Fatty Acids), including DHA and ARA**: These essential fatty acids, particularly DHA (omega-3) and ARA (omega-6), are considered crucial for cognitive, brain, and visual development.\n*   **Vitamins and Minerals**: Aptamil Pronutra is enriched with vitamins A, C, and D, which are essential for immune system support, as well as iron, calcium, and zinc, contributing to healthy growth, bone development, and the prevention of iron-deficiency anemia.\n*   **Other Nutrients**: The formulation also includes taurine and L-carnitine.\n\nScientific studies have investigated the effectiveness of Aptamil Pronutra. For instance, a study published in *Nutrition* (2021) indicated that Aptamil Pronutra, containing a prebiotic mixture of scGOS/lcFOS, supported adequate growth and was well-tolerated among healthy Chinese infants, with growth and gastrointestinal tolerance similar to breastfed infants. Aptamil formulas are also developed to avoid ingredients like corn syrup solids and artificial preservatives, which some parents prefer to limit.\n\nHowever, it is important to note that while Aptamil and similar formulas are scientifically developed and undergo rigorous testing, the European Food Safety Authority (EFSA) concluded in 2014 that there was no evidence for health benefits from the addition of prebiotic oligosaccharides to infant or follow-on formula. Despite this, Aptamil continues to be a widely recognized and trusted brand in infant nutrition, with a commitment to ongoing research and innovation.\n\nIt is always recommended to consult with healthcare professionals to determine the most suitable feeding option for an infant.\n---\nAptamil\'s Pronutra formulation is designed to support infant development by incorporating a blend of nutrients inspired by breast milk research. The formula aims to provide comprehensive nutrition for babies, particularly when breastfeeding is not possible or as a supplement.\n\nKey components and their intended benefits for infant development include:\n*   **DHA (Omega-3)**: This essential structural lipid is included to support normal early visual and neurological development, and its presence in infant formula is often mandated by regulations.\n*   **Prebiotics (GOS/FOS)**: Aptamil Pronutra contains a patented blend of galactooligosaccharides (GOS) and fructooligosaccharides (FOS). These fibers are designed to mimic human milk oligosaccharides, promoting a resilient infant microbiome and supporting digestive health, which in turn contributes to immune system function.\n*   **Vitamins and Minerals**: The formulation is enriched with essential vitamins such as A, C, and D, as well as iron. These are crucial for immune system support, healthy growth, and brain and visual development.\n*   **Lactofidus® Process**: Some Pronutra PRE formulas utilize this process, which involves natural lactic acid bacteria to pre-digest some milk components, aiming for optimal digestibility for developing digestive systems.\n*   **Absence of Palm Oil**: Aptamil Pronutra formulas often omit palm oil, using a balanced blend of vegetable oils instead, which is highlighted for better digestibility.\n\nAptamil states that its Pronutra formulation is based on extensive research and aims to meet the specific nutritional needs of infants at various stages of development, supporting healthy growth, digestion, immune function, and brain development. The brand emphasizes its commitment to continuous research and innovation in infant nutrition.\n---\nAptamil\'s Pronutra formulation is designed to support infant development by providing a blend of nutrients inspired by breast milk. The effectiveness of these formulations is supported by their inclusion of key ingredients and some clinical findings related to growth and digestive health.\n\nAptamil Pronutra formulations contain essential nutrients such as DHA (Omega-3), which is crucial for normal early visual and neurological development and is a mandatory ingredient in infant formulas by law. They also include a patented blend of Galacto-oligosaccharides (GOS) and Fructo-oligosaccharides (FOS) prebiotics, which are designed to mimic human milk oligosaccharides and promote a resilient infant microbiome, aiding digestive health. Additionally, the formulations are enriched with vitamins A, C, and D, and iron, which are vital for immune system support and overall growth.\n\nClinical studies, such as the LIFE study, have investigated the impact of Aptamil formulas. One study comparing Aptamil Pronutra with another Aptamil formula (Aptamil Essensis Partially Hydrolysed Protein) and a breastfed group found similar daily weight gain, infant growth (length and head circumference), and gastrointestinal tolerance across all three groups. This suggests that Aptamil Pronutra can support adequate growth in healthy, term infants comparable to breastfed infants. Research also indicates that formulas with a specific blend of synbiotics (a combination of prebiotics and probiotics) can contribute to a gut microbiota that more closely resembles that of breastfed babies, potentially playing a role in the development of the digestive and immune systems.\n\nHowever, it is important to note that while manufacturers often add new ingredients to infant formulas to mimic breast milk, the European Food Safety Authority (EFSA) has concluded that there is no definitive evidence for health benefits from the addition of prebiotic oligosaccharides to infant or follow-on formula.\n\nAptamil Pronutra is developed based on extensive research and aims to provide complete nutrition, with some formulations being free from palm oil and corn syrup. While breast milk is recognized as the best nutrition for infants, Aptamil Pronutra is positioned as a scientifically advanced option for situations where breastfeeding is not possible or as a supplement. Parents often choose Aptamil for its European regulatory standards, ingredient transparency, and its inclusion of components believed to support healthy growth, digestion, immune function, and brain development.\n---\nAptamil\'s Pronutra formulation is designed to support infant development by providing a blend of nutrients inspired by breast milk research. The formulation includes several key ingredients aimed at contributing to various aspects of a baby\'s growth and health.\n\nKey components and their intended benefits include:\n*   **DHA (Omega-3)**: This essential structural lipid is mandatory by law for all infant formulas and is included to support normal early visual and neurological development.\n*   **Patented GOS/FOS Prebiotics**: This specialized fiber mix is designed to mimic the structure of human milk oligosaccharides, promoting a resilient infant microbiome and supporting digestive health. Some parents have reported smoother digestion for babies struggling with gas, constipation, or tummy discomfort after switching to formulas with prebiotic blends, though individual results can vary. However, it\'s worth noting that the European Food Safety Authority (EFSA) has concluded there is no evidence for health benefits from the addition of prebiotic oligosaccharides to infant or follow-on formula.\n*   **Vitamins and Minerals**: Aptamil Pronutra contains essential systemic vitamins such as A, C, and D, along with iron, calcium, and zinc. These are intended to support the immune system, bone development, and overall growth.\n*   **Lactofidus® Process**: This proprietary process is used in some Pronutra formulations to ensure optimal digestibility and tolerability for developing digestive systems.\n*   **No Palm Oil**: Many Aptamil Pronutra formulas are made without palm oil, utilizing high-quality vegetable alternatives.\n\nAptamil Pronutra is often presented as a complete nutritional source when breastfeeding is not possible or as a supplement to breastfeeding. It is formulated to be fed on demand, similar to breast milk. Aptamil states that its formulas are based on over 40 years of research.\n\nWhile Aptamil and similar European formulas are often sought out by parents for their ingredient philosophy, which may include avoiding corn syrup solids and artificial preservatives found in some other brands, it is important to remember that breastfeeding is considered the best for babies, providing ultimate nutrition and protection from illness. The World Health Organization (WHO) recommends exclusive breastfeeding for the first six months. It is recommended that Aptamil formulas be used only on the advice of a doctor.\n---\nAptamil\'s Pronutra formulation is designed to support infant development through a blend of essential nutrients, drawing inspiration from the composition of breast milk. The formula is developed based on extensive research and aims to provide comprehensive nutritional support for babies from birth.\n\nKey components of Aptamil Pronutra and their purported benefits include:\n*   **DHA (Omega-3)**: This essential structural lipid is included to support normal early visual and neurological development.\n*   **Patented GOS/FOS Prebiotics**: This specialized fiber mix is designed to mimic the structure of human milk oligosaccharides, promoting a resilient infant microbiome and supporting digestive health. Some studies suggest that specific blends of synbiotics (probiotics and prebiotics) can contribute to a gut microbiota closer to that of breastfed babies.\n*   **Vitamins A, C, and D**: These vitamins are crucial for immune system support, healthy growth, and overall development.\n*   **LCP Milupan®**: This component, along with essential fatty acids, taurine, L-carnitine, and iron, contributes to optimal health and development.\n*   **Lactofidus® process**: This proprietary process is used in some Pronutra formulations to support excellent tolerability for developing digestive systems.\n\nAptamil claims that its Pronutra formulations support immune system, brain, and eye health, as well as digestive health. They are formulated to provide all necessary macronutrients when breastfeeding is not possible and are designed to be gentle on the developing digestive system. Aptamil Pronutra is also available in "PRE" formulations, which can be given on demand like breast milk, and different stages tailored to a baby\'s evolving nutritional needs.\n\nA study comparing Aptamil Pronutra with another formula and a breastfed group found similar daily weight gain, infant growth, and gastrointestinal tolerance, suggesting its suitability for healthy term infants. This research indicates that the formula can support adequate growth and is well-tolerated.\n\nHowever, it is important to note that while many claims are made about the benefits of adding prebiotics to infant milks, the European Food Safety Authority (EFSA) concluded in 2014 that there is no evidence for health benefits from the addition of prebiotic oligosaccharides to infant or follow-on formula. Despite this, Aptamil continues to incorporate prebiotics, citing their role in promoting a resilient infant microbiome.\n\nAptamil emphasizes its commitment to scientific research and collaboration with experts to continuously evolve its formulas, aiming to provide optimal nutrition for infants. The brand also highlights that its formulas are often free from ingredients like palm oil, sucrose, gluten, and crystalline sugar, which some parents prefer to avoid.\n---\nAptamil\'s Pronutra formulation is designed to support various aspects of infant development through a blend of key nutrients, drawing inspiration from the nutritional composition of breast milk. The effectiveness of this formulation is attributed to its specific ingredients, particularly Docosahexaenoic Acid (DHA) and a unique blend of prebiotics (scGOS/lcFOS), alongside essential vitamins and minerals.\n\n**Key Components and Their Reported Benefits:**\n\n*   **DHA (Docosahexaenoic Acid):** This omega-3 fatty acid is a critical structural component for the development of the brain and eyes. Studies suggest that formula supplemented with DHA can contribute to higher cognitive skills and improved visual acuity in infants. However, some research indicates that while visual acuity improvements are more consistently observed, the impact on overall mental and motor development in term infants has shown inconsistent results in randomized controlled trials.\n*   **Prebiotics (scGOS/lcFOS):** Aptamil Pronutra includes a patented blend of short-chain galactooligosaccharides (scGOS) and long-chain fructooligosaccharides (lcFOS). These prebiotics are intended to foster a healthy gut microbiota, mimicking that of breastfed infants, which is crucial for digestive and immune system development. Research indicates that this prebiotic blend can lead to softer stools, similar to those of breastfed babies, and may help reduce the incidence of certain infections and allergic manifestations. A study involving Aptamil Pronutra also demonstrated that it supported adequate growth in infants, with outcomes comparable to those of breastfed babies.\n*   **Essential Vitamins and Minerals:** The formulation is fortified with a range of vitamins (A, C, D, E, B vitamins, K) and minerals (iron, calcium, zinc, potassium, magnesium, copper, manganese, selenium, iodine) to support overall growth, immune function, and bone development.\n\nAptamil Pronutra is marketed as a nutritionally complete infant formula, suitable as a sole source of nutrition when breastfeeding is not possible or as a supplement. It is developed based on extensive scientific research, with some sources citing over 40 years of expertise in infant nutrition.\n\n**Comparison to Breast Milk:**\n\nWhile Aptamil Pronutra aims to closely replicate the nutritional profile of breast milk, it is important to note that breast milk is widely considered the "gold standard" for infant nutrition. Breast milk contains dynamic biological components that cannot be fully replicated in formula, and studies have shown that breastfed infants may exhibit more mature brain myelination patterns and potentially higher neurodevelopmental scores. The long-term health implications of differences in gut microbiota function between breastfed and formula-fed infants are also an ongoing area of research.\n\nIn conclusion, Aptamil\'s Pronutra formulation includes ingredients that are scientifically recognized for their roles in infant development, and some studies support its effectiveness in promoting healthy growth, gut health, and visual development. However, it is consistently emphasized that breast milk remains the optimal form of nutrition for infants.\n---\nAptamil\'s Pronutra formulation is designed to be effective in supporting various aspects of infant development, drawing on extensive research in infant nutrition. The formula aims to provide comprehensive nutrients for babies from birth, particularly when breastfeeding is not possible or as a supplement to it.\n\nKey aspects of Aptamil Pronutra\'s effectiveness for infant development include:\n*   **Brain and Visual Development** The formulation includes DHA (Omega-3), an essential fatty acid crucial for normal early visual and neurological development.\n*   **Immune System Support** Aptamil Pronutra contains a blend of vitamins, including A, C, and D, along with prebiotics (GOS/FOS), which are intended to contribute to the normal function of the immune system.\n*   **Digestive Health** The patented GOS/FOS prebiotics in Aptamil Pronutra are designed to mimic human milk oligosaccharides, promoting a resilient infant microbiome and supporting digestive health. Some formulations, like Aptamil Pronutra PRE, are also engineered for optimal digestibility and are gentle on the developing digestive system.\n*   **Overall Growth and Development** The formula provides essential macronutrients and a range of vitamins and minerals, such as iron and LCPs, to support healthy growth and development. Aptamil Pronutra is developed based on scientific research to ensure babies receive the right nutrients during critical growth stages.\n*   **Inspired by Breast Milk** Aptamil\'s formulations are inspired by 50 years of breast milk research, aiming to closely mirror its nutritional profile and provide a highly tolerable foundation for early infant development.\n\nAptamil Pronutra is available in different stages, with formulations tailored to meet the specific nutritional needs of infants at various developmental stages, from newborns to toddlers. The "PRE" classification allows for flexible, on-demand feeding, similar to breast milk. It is also noted for using high-quality vegetable oils and omitting palm oil in some formulations.\n---\nAptamil\'s Pronutra formulation is designed to support infant development by providing a blend of nutrients intended to mirror the nutritional profile of breast milk. The company states that its formulas are based on extensive research and aim to meet the nutritional needs of growing babies.\n\nKey components of Aptamil Pronutra and their claimed benefits for infant development include:

In [38]:
len(sample)

1800539

In [40]:
for tally in df["source_type_tally"]:
    print(tally)

{'other': 4, 'video_social': 1}
{'other': 8, 'video_social': 2}
{'other': 6, 'video_social': 1}
{'other': 14, 'video_social': 1}
{'other': 8, 'video_social': 1}
{'other': 10, 'video_social': 1}
{'other': 22, 'video_social': 1, 'editorial_authority': 4, 'community_reviews': 1}
{'other': 6, 'video_social': 1}
{'other': 8, 'video_social': 2}
{'other': 11, 'video_social': 1}
{'other': 3}
{'other': 2}
{'other': 4}
{'other': 2}
{'other': 2}
{'other': 4}
{'other': 2}
{'other': 3}
{'other': 3}
{'other': 3}
{'other': 19, 'editorial_authority': 1}
{'other': 18, 'editorial_authority': 1}
{'other': 6, 'video_social': 2}
{'other': 7}
{'other': 9}
{'other': 10}
{'other': 11}
{'other': 6}
{'other': 14, 'editorial_authority': 1}
{'other': 10, 'editorial_authority': 1}
{}
{'other': 2}
{'other': 4}
{'other': 3}
{'other': 2}
{'other': 4}
{'other': 2}
{'other': 5}
{}
{}
{'other': 6, 'video_social': 1}
{'other': 9, 'video_social': 1}
{'other': 9, 'video_social': 1}
{'other': 8, 'video_social': 1}
{'other': 8, 'community_reviews': 1, 'video_social': 1}
{'other': 7, 'community_reviews': 1, 'video_social': 2}
{'other': 7, 'video_social': 1}
{'other': 7, 'video_social': 1}
{'other': 7, 'video_social': 1}
{'other': 7, 'video_social': 1}
{'other': 4}
{'other': 4}
{'other': 4}
{'other': 4}
{'other': 3}
{'other': 4}
{'other': 4}
{'other': 4}
{'other': 4}
{'other': 4}
{'other': 14, 'retailer': 1}
{'other': 13, 'community_reviews': 1, 'video_social': 1}
{'other': 13, 'community_reviews': 1, 'retailer': 1}
{'community_reviews': 1, 'other': 23, 'retailer': 1}
{'community_reviews': 1, 'other': 12, 'video_social': 1}
{'community_reviews': 1, 'other': 14, 'retailer': 1}
{'other': 12, 'retailer': 1}
{'community_reviews': 1, 'other': 12}
{'other': 12, 'retailer': 1, 'video_social': 1}
{'other': 15, 'retailer': 1}
{'other': 3}
{'other': 4}
{'other': 4}
{'other': 3}
{'other': 3}
{'other': 5}
{'other': 4}
{'other': 4}
{'other': 3}
{'other': 4}
{'other': 19}
{'other': 16}
{'other': 18}
{'other': 14, 'community_reviews': 1}
{'other': 20}
{'other': 10}
{'other': 11}
{'other': 12, 'editorial_authority': 1}
{'other': 13, 'editorial_authority': 1}
{'other': 19, 'editorial_authority': 1}
{'other': 3}
{'other': 3}
{'other': 3}
{'other': 4}
{'other': 3}
{'other': 3}
{'other': 3}
{'other': 4}
{'other': 3}
{'other': 4}
{'other': 20, 'video_social': 1}
{'other': 20}
{'other': 20, 'retailer': 1}
{'other': 13}
{'other': 12}
{'other': 15}
{'other': 13}
{'other': 18}
{'other': 12}
{'other': 11, 'video_social': 1}
{'other': 6}
{'other': 6}
{'other': 6}
{'other': 5}
{'other': 5}
{'other': 6}
{'other': 6}
{'other': 6}
{'other': 5}
{'other': 5}
{'other': 9}
{'other': 4, 'video_social': 1, 'retailer': 1}
{'other': 20, 'editorial_authority': 2, 'retailer': 1}
{'other': 5, 'retailer': 1}
{'other': 6, 'video_social': 1, 'retailer': 1}
{'other': 14, 'editorial_authority': 1}
{'other': 16, 'video_social': 1, 'retailer': 1}
{'other': 14, 'editorial_authority': 1}
{'other': 15, 'editorial_authority': 1}
{'other': 10}
{'other': 3}
{'other': 4}
{'other': 3}
{'other': 3}
{'other': 5}
{'other': 4}
{'other': 4}
{'other': 4}
{'other': 4}
{'other': 5}
{'other': 5, 'video_social': 1}
{'other': 22, 'retailer': 2}
{'other': 9, 'retailer': 1}
{'other': 9}
{'other': 4, 'community_reviews': 1, 'video_social': 1, 'retailer': 1}
{'other': 12, 'editorial_authority': 1, 'video_social': 1}
{'other': 7, 'community_reviews': 1}
{'other': 6, 'video_social': 1, 'retailer': 1}
{'other': 20, 'editorial_authority': 1, 'retailer': 1, 'video_social': 1, 'brand_owned': 1}
{'other': 8, 'video_social': 1}
{'other': 5}
{'other': 5}
{'other': 4}
{'other': 4}
{'other': 4}
{'other': 4}
{'other': 3}
{'other': 5}
{'other': 3}
{'other': 5}
{'other': 16, 'editorial_authority': 4, 'community_reviews': 1}
{'other': 15, 'editorial_authority': 3, 'brand_owned': 1}
{'other': 8, 'editorial_authority': 1, 'retailer': 1}
{'editorial_authority': 3, 'other': 13}
{'other': 14, 'editorial_authority': 2}
{'other': 17, 'editorial_authority': 2}
{'other': 6, 'editorial_authority': 1}
{'editorial_authority': 2, 'other': 10}
{'other': 16, 'editorial_authority': 2}
{'other': 15, 'editorial_authority': 2}
{'other': 4}
{'other': 4}
{'other': 4}
{'other': 4}
{'other': 4}
{'other': 5}
{'other': 5}
{'other': 5}
{'other': 5}
{'other': 4}
{'other': 13}
{'community_reviews': 1, 'other': 10, 'video_social': 1}
{'other': 7}
{'other': 9, 'community_reviews': 1}
{'other': 26}
{'other': 6}
{'other': 12, 'editorial_authority': 1}
{'other': 14, 'editorial_authority': 2}
{'other': 5}
{'other': 11}
{'other': 5}
{'other': 5}
{'other': 5}
{'other': 5}
{'other': 5}
{'other': 5}
{'other': 3}
{'other': 5}
{'other': 5}
{'other': 6}
{'community_reviews': 1, 'other': 16, 'editorial_authority': 1, 'retailer': 3}
{'other': 23, 'editorial_authority': 1}
{'other': 17}
{'other': 24, 'editorial_authority': 2, 'retailer': 2}
{'other': 23, 'editorial_authority': 3, 'retailer': 3}
{'other': 17, 'editorial_authority': 2, 'retailer': 3}
{'other': 21, 'retailer': 2}
{'other': 9}
{'other': 20, 'editorial_authority': 1, 'retailer': 3}
{'other': 17, 'editorial_authority': 3, 'retailer': 4}
{'other': 5}
{'other': 4}
{'other': 6}
{'other': 4}
{'other': 6}
{'other': 4}
{'other': 2}
{'other': 5}
{'other': 4}
{'other': 4}
{'other': 10}
{'other': 6}
{'other': 11}
{'other': 6, 'community_reviews': 1}
{'other': 8}
{'other': 18}
{'other': 6}
{'other': 17, 'editorial_authority': 1}
{'other': 17, 'editorial_authority': 2}
{'other': 17, 'community_reviews': 1, 'editorial_authority': 1}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{'other': 11, 'editorial_authority': 2}
{'other': 6, 'editorial_authority': 2}
{'other': 7, 'editorial_authority': 2}
{'other': 11, 'editorial_authority': 2, 'video_social': 1}
{'other': 11, 'editorial_authority': 4, 'video_social': 2}
{'other': 8, 'editorial_authority': 3}
{'other': 11, 'editorial_authority': 2}
{'other': 9, 'editorial_authority': 3}
{'other': 10, 'editorial_authority': 1}
{'other': 8, 'editorial_authority': 2}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{'other': 17, 'editorial_authority': 1, 'community_reviews': 1}
{'other': 22, 'editorial_authority': 1}
{'other': 9, 'editorial_authority': 1}
{'other': 8, 'editorial_authority': 1}
{'other': 8, 'editorial_authority': 1}
{'community_reviews': 1, 'other': 21, 'editorial_authority': 2}
{'other': 25, 'editorial_authority': 1, 'community_reviews': 1, 'retailer': 1}
{'other': 16, 'editorial_authority': 2}
{'other': 21, 'editorial_authority': 3}
{'other': 23, 'editorial_authority': 1, 'community_reviews': 1, 'retailer': 1}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{'community_reviews': 1, 'other': 2, 'retailer': 1, 'video_social': 1}
{'other': 4, 'video_social': 1}
{'other': 6, 'video_social': 1, 'retailer': 1}
{'other': 8, 'video_social': 1}
{'other': 13, 'brand_owned': 2, 'editorial_authority': 3, 'retailer': 1, 'video_social': 1}
{'other': 15, 'community_reviews': 2, 'video_social': 1}
{'other': 13, 'video_social': 1}
{'other': 5, 'retailer': 2, 'video_social': 1}
{'other': 5, 'video_social': 1}
{'other': 19, 'brand_owned': 1}
{'other': 4}
{'other': 5}
{'other': 5}
{'other': 5}
{'other': 4}
{'other': 5}
{'other': 4}
{'other': 4}
{'other': 6}
{'other': 4}
{'other': 12, 'video_social': 1, 'retailer': 1}
{'other': 6, 'retailer': 1, 'video_social': 1}
{'other': 6, 'community_reviews': 1, 'retailer': 1, 'video_social': 1}
{'other': 5, 'video_social': 1}
{'community_reviews': 1, 'other': 6, 'retailer': 1, 'video_social': 1}
{'other': 6, 'video_social': 1}
{'other': 8, 'video_social': 1}
{'video_social': 1, 'other': 1}
{'other': 16, 'retailer': 3, 'video_social': 1}
{'other': 7, 'video_social': 1, 'retailer': 1}
{'other': 4}
{'other': 4}
{'other': 4}
{'other': 5}
{'other': 3}
{'other': 4}
{'other': 3}
{'other': 2}
{'other': 3}
{'other': 5}
{'other': 10}
{'other': 10}
{'other': 9}
{'other': 6, 'editorial_authority': 1}
{'other': 11}
{'other': 7, 'editorial_authority': 2}
{'editorial_authority': 1, 'other': 13}
{'editorial_authority': 2, 'other': 11}
{'other': 10, 'editorial_authority': 1}
{'other': 13, 'editorial_authority': 2}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{'other': 7}
{'other': 8}
{'other': 8}
{'other': 18, 'retailer': 1}
{'other': 8}
{'other': 13, 'retailer': 1}
{'other': 5}
{'other': 11, 'retailer': 1}
{'other': 12}
{'other': 8}
{'other': 5}
{'other': 4}
{'other': 4}
{'other': 5}
{'other': 6}
{'other': 4}
{'other': 5}
{'other': 4}
{'other': 5}
{'other': 3}
{'other': 13, 'editorial_authority': 1, 'retailer': 1}
{'other': 7}
{'brand_owned': 1, 'other': 16}
{'other': 4}
{'other': 6}
{'other': 6}
{'other': 6}
{'other': 8}
{'other': 7}
{'other': 8}
{'other': 9, 'editorial_authority': 1}
{'other': 9, 'editorial_authority': 1}
{'other': 12, 'editorial_authority': 2}
{'other': 9, 'editorial_authority': 1}
{'other': 16, 'editorial_authority': 2, 'retailer': 1}
{'other': 11, 'editorial_authority': 1}
{'retailer': 2, 'other': 9, 'editorial_authority': 2}
{'other': 12, 'retailer': 2, 'editorial_authority': 2}
{'other': 11, 'editorial_authority': 1}
{'other': 10, 'editorial_authority': 2, 'retailer': 2}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{'editorial_authority': 2, 'other': 14}
{'other': 10, 'brand_owned': 1, 'editorial_authority': 1}
{'other': 11, 'editorial_authority': 2}
{'other': 9, 'editorial_authority': 2}
{'other': 11, 'editorial_authority': 3}
{'other': 10, 'editorial_authority': 2, 'retailer': 1}
{'other': 10, 'editorial_authority': 2}
{'other': 10, 'editorial_authority': 1}
{'other': 10, 'editorial_authority': 3}
{'other': 9, 'editorial_authority': 3}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{'community_reviews': 1, 'other': 7}
{'community_reviews': 1, 'other': 8}
{'other': 6, 'community_reviews': 1}
{'community_reviews': 1, 'other': 9}
{'other': 9, 'community_reviews': 1}
{'other': 7, 'community_reviews': 1}
{'other': 6, 'community_reviews': 1}
{'community_reviews': 1, 'other': 6}
{'other': 6, 'community_reviews': 1}
{'other': 6, 'community_reviews': 1}
{'other': 6}
{'other': 5}
{'other': 4}
{'other': 5}
{'other': 4}
{'other': 3}
{'other': 5}
{'other': 6}
{'other': 3}
{'other': 3}
{'community_reviews': 1, 'other': 12}
{'other': 12, 'community_reviews': 1, 'editorial_authority': 1}
{'other': 12, 'community_reviews': 1}
{'other': 10, 'community_reviews': 1}
{'other': 15, 'community_reviews': 1, 'editorial_authority': 1}
{'other': 11, 'community_reviews': 1}
{'other': 14, 'community_reviews': 1}
{'community_reviews': 2, 'other': 6}
{'other': 13, 'community_reviews': 1}
{'community_reviews': 1, 'other': 7}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{'other': 19}
{'other': 2, 'community_reviews': 1}
{'other': 6, 'retailer': 1}
{'other': 9, 'retailer': 2}
{'other': 16, 'community_reviews': 1}
{'other': 4, 'community_reviews': 1, 'retailer': 1}
{'other': 5}
{'other': 5}
{'other': 4, 'retailer': 2}
{'other': 13}
{'other': 5}
{'other': 5}
{'other': 5}
{'other': 6}
{'other': 5}
{'other': 7}
{'other': 5}
{'other': 4}
{'other': 5}
{'other': 5}
{'other': 7, 'retailer': 1, 'editorial_authority': 1}
{'other': 6, 'editorial_authority': 1}
{'other': 7}
{'other': 6, 'editorial_authority': 1}
{'other': 5, 'retailer': 1, 'editorial_authority': 1}
{'other': 6, 'retailer': 1, 'editorial_authority': 1}
{'other': 7, 'editorial_authority': 1}
{'other': 3, 'retailer': 1, 'editorial_authority': 1}
{'other': 6, 'editorial_authority': 1}
{'other': 6, 'editorial_authority': 1}
{}
{}
{}
{'other': 2}
{'other': 2}
{'other': 6}
{}
{'other': 4}
{}
{}
{'other': 8}
{'other': 8}
{'other': 12, 'community_reviews': 1}
{'other': 15}
{'other': 14}
{'other': 14, 'community_reviews': 1}
{'other': 10}
{'other': 9}
{'community_reviews': 1, 'other': 14}
{'other': 10, 'community_reviews': 1}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{'other': 9}
{'other': 9}
{'other': 9, 'editorial_authority': 1}
{'other': 15}
{'other': 12, 'editorial_authority': 1}
{'other': 10}
{'other': 11, 'editorial_authority': 2}
{'other': 16, 'editorial_authority': 1}
{'other': 11}
{'other': 16}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{'other': 11, 'editorial_authority': 1}
{'other': 10, 'editorial_authority': 1}
{'other': 13, 'editorial_authority': 1}
{'other': 7}
{'other': 9, 'editorial_authority': 1}
{'editorial_authority': 1, 'other': 9}
{'other': 9, 'editorial_authority': 1}
{'other': 10, 'editorial_authority': 1}
{'other': 7, 'editorial_authority': 1}
{'other': 11, 'editorial_authority': 1}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{'other': 8, 'editorial_authority': 1}
{'other': 8}
{'other': 9}
{'other': 7}
{'other': 8, 'community_reviews': 1}
{'other': 8, 'editorial_authority': 1}
{'other': 8, 'community_reviews': 1}
{'other': 8}
{'other': 7, 'community_reviews': 1}
{'other': 6, 'community_reviews': 1}
{'other': 4}
{'other': 3}
{'other': 5}
{'other': 3}
{'other': 4}
{'other': 4}
{'other': 4}
{'other': 4}
{'other': 4}
{'other': 2}
{'other': 8}
{'other': 9, 'editorial_authority': 1}
{'other': 8}
{'other': 10}
{'other': 10}
{'other': 6}
{'other': 9}
{'other': 9}
{'other': 10}
{'other': 10, 'editorial_authority': 2}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{'other': 14}
{'other': 17, 'editorial_authority': 1}
{'editorial_authority': 1, 'other': 10}
{'other': 14, 'editorial_authority': 1}
{'other': 9}
{'other': 13, 'editorial_authority': 1}
{'other': 10}
{'other': 13}
{'other': 12}
{'other': 8}
{'other': 9, 'video_social': 1}
{'other': 16}
{'other': 12, 'editorial_authority': 1}
{'other': 13}
{'other': 10}
{'other': 12}
{'other': 16}
{'other': 11}
{'other': 17, 'editorial_authority': 1}
{'other': 16, 'editorial_authority': 1}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}

In [41]:
g = df.groupby("query")["mentioned"].mean()
g

query
Aptamil vs Enfamil for infant immunity and cognitive development       1.0
Aptamil vs Kendamil: proprietary ingredient technology comparison      1.0
Aptamil vs Similac: which has better clinical credibility?             1.0
Are generic baby formulas as good as name brands?                      0.0
Are low-iron formulas better for constipation?                         0.0
Best baby formula for first-time parents                               0.0
Best baby formula for newborns                                         0.0
Best baby formula for sensitive stomach?                               0.1
Best formula for colic and gas?                                        0.1
Concerns about heavy metals in infant formula                          0.0
Does Aptamil provide a full spectrum of infant nutrition needs?        1.0
Formula for babies with dairy allergies?                               0.1
Formula for babies with reflux or spit-up?                             0.5
Formula for babies with sensitive stomachs                             0.0
Formula for constipation relief?                                       0.0
How to choose formula for a newborn?                                   0.0
How to choose the best baby formula?                                   0.0
How to pick an age-appropriate baby formula?                           0.0
Hypoallergenic formula recommendations for allergies?                  0.0
Infant formula for health-conscious parents                            0.0
Is Aptamil's Pronutra formulation effective for infant development?    1.0
Is baby formula safe?                                                  0.0
Lactose-free formula benefits for sensitive tummies?                   0.0
Should I be concerned about GMOs in baby formula?                      0.0
What are Aptamil's claims regarding early-life immunity?               1.0
What are the best gentle formula options?                              0.0
What are the best plant-based formula options?                         0.0
What is the best formula for combination feeding?                      0.0
What is the best infant formula for brain development?                 0.0
What to consider when switching baby formula?                          0.0
What to do if baby is gassy after switching formula?                   0.0
Which baby formula ingredients cause constipation?                     0.0
Name: mentioned, dtype: float64

In [42]:
per = df.groupby(["engine","query"])["is_first"].mean().unstack(0)
per

engine,azure/gpt-4o,gemini-2.5-flash
query,,
Aptamil vs Enfamil for infant immunity and cognitive development,1.0,1.0
Aptamil vs Kendamil: proprietary ingredient technology comparison,1.0,1.0
Aptamil vs Similac: which has better clinical credibility?,1.0,1.0
Are generic baby formulas as good as name brands?,0.0,0.0
Are low-iron formulas better for constipation?,0.0,0.0
Best baby formula for first-time parents,0.0,0.0
Best baby formula for newborns,0.0,0.0
Best baby formula for sensitive stomach?,0.0,0.2
Best formula for colic and gas?,0.0,0.0
Concerns about heavy metals in infant formula,0.0,0.0
Does Aptamil provide a full spectrum of infant nutrition needs?,1.0,1.0
Formula for babies with dairy allergies?,0.0,0.0
Formula for babies with reflux or spit-up?,0.0,0.5
Formula for babies with sensitive stomachs,0.0,0.0
Formula for constipation relief?,0.0,0.0
How to choose formula for a newborn?,0.0,0.0
How to choose the best baby formula?,0.0,0.0
How to pick an age-appropriate baby formula?,NaN,0.0
Hypoallergenic formula recommendations for allergies?,NaN,0.0
Infant formula for health-conscious parents,0.0,0.0
Is Aptamil's Pronutra formulation effective for infant development?,1.0,1.0
Is baby formula safe?,0.0,0.0
Lactose-free formula benefits for sensitive tummies?,0.0,0.0
Should I be concerned about GMOs in baby formula?,0.0,0.0
What are Aptamil's claims regarding early-life immunity?,1.0,1.0
What are the best gentle formula options?,0.0,0.0
What are the best plant-based formula options?,0.0,0.0
What is the best formula for combination feeding?,0.0,0.0
What is the best infant formula for brain development?,0.0,0.0
What to consider when switching baby formula?,0.0,0.0
What to do if baby is gassy after switching formula?,0.0,0.0
Which baby formula ingredients cause constipation?,0.0,0.0

In [43]:
engines = list(per.columns)
agree_win = per[(per > 0.5).all(axis=1)].index.tolist()      # win everywhere
agree_lose = per[(per == 0).all(axis=1)].index.tolist()      # lose everywhere
diverge = per[per.max(axis=1) - per.min(axis=1) > 0.4].index.tolist()
engines, agree_win,agree_lose,diverge

(['azure/gpt-4o', 'gemini-2.5-flash'],
 ['Aptamil vs Enfamil for infant immunity and cognitive development',
  'Aptamil vs Kendamil: proprietary ingredient technology comparison',
  'Aptamil vs Similac: which has better clinical credibility?',
  'Does Aptamil provide a full spectrum of infant nutrition needs?',
  "Is Aptamil's Pronutra formulation effective for infant development?",
  "What are Aptamil's claims regarding early-life immunity?"],
 ['Are generic baby formulas as good as name brands?',
  'Are low-iron formulas better for constipation?',
  'Best baby formula for first-time parents',
  'Best baby formula for newborns',
  'Best formula for colic and gas?',
  'Concerns about heavy metals in infant formula',
  'Formula for babies with dairy allergies?',
  'Formula for babies with sensitive stomachs',
  'Formula for constipation relief?',
  'How to choose formula for a newborn?',
  'How to choose the best baby formula?',
  'Infant formula for health-conscious parents',
  'Is baby formula safe?',
  'Lactose-free formula benefits for sensitive tummies?',
  'Should I be concerned about GMOs in baby formula?',
  'What are the best gentle formula options?',
  'What are the best plant-based formula options?',
  'What is the best formula for combination feeding?',
  'What is the best infant formula for brain development?',
  'What to consider when switching baby formula?',
  'What to do if baby is gassy after switching formula?',
  'Which baby formula ingredients cause constipation?'],
 ['Formula for babies with reflux or spit-up?'])

In [45]:
import json
import re
from pathlib import Path
from collections import defaultdict

In [46]:
 comp_snippets = defaultdict(list)

In [47]:
comp_snippets

defaultdict(list, {})

In [48]:
raw_path = "/Users/thomasjoseph/Desktop/JMJTL/Projects/Gen_ai/GEO/geo_discovery/geo_projects/danone/aptamil/audit_raw.jsonl"

In [52]:
query_filter = None
comp_names = ["SMA","Enfamil","aptamil"]
for line in open(raw_path, encoding="utf-8"):
    try:
        r = json.loads(line)
    except Exception:
        continue
    if not r.get("success"):
        continue
    if query_filter and query_filter.lower() not in r.get("query", "").lower():
        continue                                    # only the relevant query's responses
    text = r.get("response_text", "")
    #print(text)
    for sent in re.split(r'(?<=[.!?])\s+', text):
        low = sent.lower()
        for cname in comp_names:
            if cname.lower() == target_brand.lower():
                continue
            if cname.lower() in low and len(sent.strip()) > 30:
                comp_snippets[cname].append(sent.strip())

In [53]:
comp_snippets

defaultdict(list,
            {'SMA': ['**Brain and Immune Development**: Aptamil links immune system support with cognitive development, promoting the idea of "stronger immunity, smarter future" through its advanced nutritional engineering [RSIS International](https://rsisinternational.org/journals/ijriss/uploads/vol10-iss21-pg1255-1269-202608_pdf.pdf).',
              'Specialty Formulas**\n- **Kendamil**: Offers a smaller range of products, including Classic, Organic, Goat Milk, and Comfort formulas.',
              'Research and Development**\n- **Kendamil**: Focuses on traditional methods and natural ingredients, with a smaller-scale, family-run production model in the UK [Kendamil Blog](https://kendamil.com/blogs/blog/kendamil-vs-aptamil-which-follow-on-formula-is-right-for-your-baby).',
              '*   **Hydrolyzed Formulas (Hypoallergenic):** For babies with milk protein allergies or significant digestive issues, hydrolyzed formulas have proteins broken down into smaller pieces, making them less likely to cause allergic reactions.',
              '*   **Extensively Hydrolyzed Formulas:** These are considered truly hypoallergenic and are for babies with severe allergies to milk protein, as the proteins are broken into very small fragments.',
              '**Hydrolyzed Formulas (Extensively or Partially):**\n    *   In these formulas, proteins are broken down into smaller pieces, making them easier to digest and less likely to cause allergic reactions.',
              '*   **Hydrolyzed Formulas (Partially or Extensively):** Also known as "gentle" or "hypoallergenic" formulas, these have proteins that are broken down into smaller pieces, making them easier to digest and less likely to cause allergic reactions.',
              'In these formulas, the proteins are broken down into smaller pieces, making them less likely to trigger an allergic reaction.',
              '*   **Hypoallergenic (Extensively Hydrolyzed):** Designed for babies with milk protein allergies or sensitivities, where the proteins are broken down into smaller, easier-to-digest particles.',
              "Protein Type:**\n*   **Partially Hydrolyzed Proteins:** In these formulas, the cow's milk proteins are partially broken down into smaller pieces, making them easier for a baby to digest.",
              "*   **Extensively Hydrolyzed Proteins:** For babies with more significant sensitivities or suspected cow's milk protein allergy, extensively hydrolyzed formulas break down proteins into even smaller components.",
              "Gentle/Partially Hydrolyzed Formulas**\nThese formulas contain cow's milk proteins that have been partially broken down (hydrolyzed) into smaller fragments, making them easier to digest.",
              "Extensively Hydrolyzed Protein Formulas (Hypoallergenic)**\nFor babies with a suspected or confirmed cow's milk protein allergy, extensively hydrolyzed formulas break down proteins into very small pieces to minimize allergic reactions.",
              "The proteins in goat milk form a smaller, softer curd in the stomach compared to cow's milk, which may make it easier to digest for some infants.",
              'The proteins in these formulas are extensively hydrolyzed, meaning they are broken down into very small pieces that are less likely to trigger an allergic reaction.',
              'The protein in goat milk is believed to produce smaller, softer curds, which may be gentler on sensitive stomachs.',
              'This process makes the protein molecules smaller, mimicking the size of proteins in breast milk, which can be easier for an immature digestive system to process.',
              "*   **Extensively Hydrolyzed Proteins:** For more significant sensitivities or suspected cow's milk protein allergy, extensively hydrolyzed formulas have proteins broken down into much smaller pieces, reducing the likelihood of an allergic reaction.",
              "Hydrolyzed proteins are cow's milk proteins that have been broken down into smaller pieces, making them easier for a baby's immature digestive system to process and reducing the likelihood of an allergic reaction.",
              "**Partially Hydrolyzed Formulas**\n    These formulas contain cow's milk proteins that have been partially broken down into smaller pieces, making them easier to digest.",
              'Key components and types of formulas include:\n\n*   **Hydrolyzed Proteins:** These formulas contain proteins that have been broken down (hydrolyzed) into smaller, more digestible pieces.',
              '**Holle Goat Milk Formula**  \n   - Goat milk formulas are often easier to digest due to smaller fat globules.',
              '**Bubs Goat Milk Formula**  \n   - A goat milk-based formula that is easier to digest due to smaller fat globules.',
              '**Holle Goat Milk Formula**  \n   - Made with goat milk, which has smaller fat globules for easier digestion.',
              "*   **Partially Hydrolyzed Formulas:** These formulas have cow's milk proteins broken down into smaller pieces, making them easier to digest.",
              "*   **Goat Milk-Based Formulas:** Goat milk naturally contains A2 beta-casein protein, which is smaller and easier to digest than the proteins in cow's milk.",
              'Its fat particles are also smaller, forming a softer curd in the stomach, which can lead to less spitting up and discomfort.',
              "Specialized Formulas (Consult a Pediatrician)**\nIf a baby has specific medical needs, such as a diagnosed allergy or condition, a pediatrician might recommend specialized formulas:\n\n*   **Extensively Hydrolyzed Formulas:** For babies with a confirmed cow's milk protein allergy, these formulas have proteins broken down into very small pieces to reduce allergic reactions.",
              "Gentle/Partially Hydrolyzed Formulas\n\n*   **Description:** These formulas contain cow's milk proteins that have been partially broken down (hydrolyzed) into smaller pieces.",
              'They come in different forms based on the extent of protein breakdown:\n\n*   **Extensively Hydrolyzed Formulas:** The milk proteins are extensively broken down into very small fragments, making them less likely to cause an allergic reaction.',
              '*   **Amino Acid-Based Formulas:** In these formulas, proteins are completely broken down into individual amino acids, the smallest building blocks of protein.',
              'Lifestyle adjustments like positional changes and smaller, more frequent feeds are often the first recommendations.',
              "*   **Protein Sources:** Protein in infant formula can be full-sized (like cow's milk or soy-based) or partially hydrolyzed (broken down into smaller proteins, closer to those in breast milk).",
              '*   **Hydrolyzed Formulas (Partially or Extensively):** In these formulas, proteins are broken down into smaller pieces, making them easier to digest and less likely to cause allergic reactions.',
              '*   **Extensively Hydrolyzed Formulas (Hypoallergenic):** These formulas have proteins broken down into smaller pieces, making them easier to digest and less likely to cause allergic reactions.',
              'These formulas often feature partially hydrolyzed proteins, meaning the milk proteins are broken down into smaller pieces for easier digestion, and may have reduced lactose.',
              '**Alternative Options:**\n\n*   **Goat Milk-Based Formulas (e.g., Kendamil Goat Milk Formula, Aussie Bubs Goat Milk Formula):** Goat milk formulas are often considered easier to digest due to smaller fat particles and a softer curd formation in the stomach, potentially leading to less spitting up.',
              '*   **Iron (in sensitive infants)**: While generally, the iron content in infant formula is not considered a primary cause of constipation, some sources indicate that it can contribute to firmer stools in a small number of particularly sensitive infants.',
              'Formulas with partially hydrolyzed proteins, where the proteins are broken down into smaller, more easily digestible pieces, are often recommended for babies experiencing constipation.',
              'Heavy metals are naturally present in the environment, including soil, water, and food, so small amounts can make their way into a wide range of products.',
              'Even small amounts can have profound neurological impacts, leading to lower IQ, attention deficit disorder, hyperactivity, and behavioral problems.',
              'These substances can pose significant health risks to infants due to their developing organ systems and smaller body sizes.',
              'While small amounts of these metals are often unavoidable, chronic exposure to higher levels can pose health risks, particularly for infants and young children, whose developing brains and bodies are more vulnerable.',
              '*   **Hypoallergenic Formulas (Extensively Hydrolyzed or Amino Acid-Based):** These formulas have proteins broken down into smaller pieces, making them easier to digest and less likely to cause allergic reactions in babies with severe milk protein allergies.',
              "*   **For Sensitivity and Digestive Issues:**\n    *   **Partially Hydrolyzed Formulas (Gentle/Comfort Formulas):** These formulas have cow's milk proteins (whey and casein) broken into smaller pieces, making them easier to digest and potentially reducing discomfort from gas, fussiness, and crying.",
              "*   **For Allergies:**\n    *   **Extensively Hydrolyzed Formulas:** For babies with a diagnosed cow's milk protein allergy (CMPA), these formulas have milk proteins broken down into very small pieces, making them much less likely to cause an allergic reaction.",
              '*   **Extensively Hydrolyzed Formula:** In these formulas, the proteins are broken down into smaller pieces, making them easier to digest for babies with protein sensitivities or allergies.',
              '*   **Extensively Hydrolyzed Formulas:** For babies with diagnosed milk protein allergies or significant digestive problems, these formulas have proteins broken down into very small pieces, making allergic reactions less likely.',
              '*   **Hydrolyzed Formulas:** These formulas have proteins that are broken down into smaller pieces.',
              "*   **Partially Hydrolyzed Formulas:** These break down cow's milk proteins into smaller fragments, making them easier to digest and potentially reducing discomfort like gas and fussiness.",
              "*   **Extensively Hydrolyzed Formulas:** These break cow's milk proteins into very small peptides and are designed for infants with cow's milk protein allergies (CMPA) or severe digestive issues.",
              "*   **Partially Hydrolyzed Formula (Gentle/Comfort Formulas):** In these formulas, cow's milk proteins are broken down into smaller pieces, making them easier to digest and potentially reducing discomfort like gas, fussiness, and crying.",
              "*   **Extensively Hydrolyzed Formula (Hypoallergenic Formulas):** Designed for infants with a cow's milk protein allergy, these formulas have proteins broken down into very small pieces to virtually eliminate allergic reactions.",
              "*   **Partially Hydrolyzed Formulas (Gentle/Sensitive):** In these formulas, cow's milk proteins are broken into smaller pieces, making them easier to digest and potentially reducing discomfort like gas and fussiness.",
              "*   **Extensively Hydrolyzed Formulas (Hypoallergenic):** For babies diagnosed with a cow's milk protein allergy (CMPA), these formulas have proteins broken down into very small pieces, significantly reducing the likelihood of an allergic reaction.",
              '*   **Hydrolyzed Formulas:** In these formulas, the milk proteins are broken down into smaller pieces, making them easier to digest and less likely to cause an allergic reaction.',
              '*   **Extensively Hydrolyzed Formulas:** These formulas have proteins broken down into very small pieces, making them hypoallergenic.',
              "*   **Partially Hydrolyzed Formulas (Gentle Formulas):** In these formulas, cow's milk proteins are broken down into smaller pieces, making them easier to digest and potentially reducing discomfort like gas, fussiness, and crying.",
              '*   **Extensively Hydrolyzed Formulas (Hypoallergenic Formulas):** The milk proteins in these formulas are broken down into very small pieces, significantly reducing the chance of an allergic reaction.',
              '- **Hydrolyzed Formula**: Proteins are broken down into smaller pieces, making it easier to digest.',
              '- **Hydrolyzed Formula**: Proteins in these formulas are broken down into smaller pieces, making them easier to digest.',
              '- **Hydrolyzed Formula**: These formulas contain proteins that are broken down into smaller pieces, making them easier to digest.',
              '- **Hydrolyzed Formula**: Proteins are broken down into smaller pieces, making it easier for babies with allergies or digestive issues to tolerate.',
              '- **Hydrolyzed Formula**: Proteins are broken down into smaller pieces to make digestion easier.',
              '- **Hydrolyzed Formula**: Proteins are broken down into smaller pieces for babies with allergies or digestive issues.',
              '- **Hydrolyzed Formula**: These formulas contain proteins that are broken down into smaller pieces, making them easier to digest.',
              '- **Hydrolyzed Formula**: Proteins are broken down into smaller parts, making it easier for babies with allergies or digestive issues to tolerate.',
              "Key features to look for in formulas for sensitive stomachs include:\n*   **Partially Hydrolyzed Protein** These formulas contain proteins that are already broken down into smaller pieces, making them easier for a baby's digestive system to process.",
              'Hydrolyzed formulas contain proteins that are already broken down into smaller fragments, making them easier for an immature digestive system to process.',
              'The proteins are extensively hydrolyzed, meaning they are broken into smaller pieces to be less allergenic and easier to digest.',
              'They often feature:\n    *   **Hydrolyzed Proteins:** The proteins are broken down into smaller pieces, making them easier to digest for immature digestive systems.',
              "Formulas for sensitive stomachs generally fall into a few categories:\n\n### Partially Hydrolyzed Formulas\nThese formulas contain cow's milk proteins that have been partially broken down into smaller pieces, making them easier for some babies to digest.",
              "*   **Extensively Hydrolyzed Formulas:** These are considered hypoallergenic and are suitable for infants with diagnosed cow's milk protein allergy (CMPA) or severe sensitivities, as the proteins are broken into very small pieces.",
              '*   **For Colic, Gas, and Fussiness (Gentle/Comfort Formulas)**: These formulas often feature partially hydrolyzed proteins (proteins broken down into smaller pieces for easier digestion) and sometimes reduced lactose content.',
              "*   **For Cow's Milk Protein Sensitivity or Allergy (Hydrolyzed and Extensively Hydrolyzed Formulas)**: If a cow's milk protein allergy is suspected, extensively hydrolyzed formulas (where proteins are broken down into very small pieces) or amino acid-based formulas may be necessary.",
              'Formulas designed for sensitive stomachs often feature:\n*   **Partially Hydrolyzed Proteins:** These formulas contain proteins that are already broken down into smaller pieces, making them easier to digest.',
              'These formulas have extensively hydrolyzed proteins, meaning the milk proteins are broken down into very small fragments to minimize allergic reactions.',
              'Hydrolyzed proteins are broken down into smaller pieces, making them easier to digest.',
              '**Key Ingredients to Look For:**\n\n*   **Hydrolyzed Proteins:** These proteins are pre-digested, meaning they are broken down into smaller pieces, which can significantly reduce gas and bloating.',
              "Partially Hydrolyzed Formulas (Gentle Formulas)**\nThese formulas contain cow's milk proteins that have been partially broken down into smaller pieces, making them easier for a baby's developing digestive system to handle.",
              '**Bubs Goat Milk Formula**  \n   - Made with goat milk, which has smaller fat globules and is easier to digest.',
              '**Holle Goat Milk Formula**  \n   - Goat milk formulas are often gentler on sensitive stomachs due to their smaller fat globules and different protein structure.',
              '**Holle Goat Milk Formula**  \n   - Goat milk formulas are often gentler on sensitive stomachs due to their smaller fat globules and different protein structure.',
              'These "sensitive" formulas typically have less lactose than regular cow\'s milk-based formulas and may contain partially hydrolyzed proteins, which are proteins broken down into smaller pieces for easier digestion.',
              "These formulas often feature partially hydrolyzed proteins, meaning the proteins are broken down into smaller pieces to make them easier for a baby's immature digestive system to process.",
              "This means the proteins are broken down into smaller pieces, making them easier for a baby's digestive system to handle.",
              "These formulas typically feature partially hydrolyzed proteins, which are broken down into smaller pieces to be easier for a baby's digestive system to handle.",
              'When choosing a gentle formula, it\'s important to understand that "gentle" often refers to formulas with partially hydrolyzed proteins, meaning the milk proteins are broken down into smaller pieces to make them easier to digest.',
              'Key characteristics and ingredients to look for in gentle formulas include:\n*   **Partially Hydrolyzed Proteins** These are milk proteins that have been broken down into smaller pieces, making them easier to digest than the larger, intact proteins found in standard formulas.',
              'Here are some of the top gentle formula options and their distinguishing features:\n\n**Key Characteristics of Gentle Formulas:**\n\n*   **Partially Hydrolyzed Protein:** Many gentle formulas contain partially hydrolyzed whey protein, meaning the proteins are broken down into smaller pieces, making them easier for a baby to digest.',
              "Top recommendations include:\n*   **Bobbie Organic Gentle Infant Formula**\n*   **HiPP Comfort Formula**\n*   **HiPP HA Formula**\n*   **Kendamil Goat Milk Formula**\n*   **Earth's Best Organic Gentle Formula**\n*   **Similac Pro Total Comfort**\n*   **Enfamil Gentlease**\n*   **Baby's Only A2 Organic Milk Infant Formula**\n*   **Enfamil Reguline**\n*   **Gerber GoodStart GentlePro**\n*   **Gerber GoodStart SoothePro**\n\nThese formulas often contain proteins broken down into smaller pieces to aid digestion.",
              'These formulas have milk proteins broken down into very small pieces, making them less likely to trigger an allergic reaction and are typically lactose-free.',
              "Extensively hydrolyzed formulas are particularly recommended if a cow's milk protein allergy is suspected, as they break proteins into very small pieces that are less likely to trigger an allergic reaction.",
              "Formulas designed to alleviate colic and gas often feature specific characteristics:\n\n*   **Hydrolyzed Proteins** These formulas contain proteins that have been broken down into smaller pieces, making them easier for a baby's immature digestive system to process.",

In [54]:
comp_snippets.keys()

dict_keys(['SMA', 'Enfamil'])

In [56]:
comp_snippets['SMA']

['**Brain and Immune Development**: Aptamil links immune system support with cognitive development, promoting the idea of "stronger immunity, smarter future" through its advanced nutritional engineering [RSIS International](https://rsisinternational.org/journals/ijriss/uploads/vol10-iss21-pg1255-1269-202608_pdf.pdf).',
 'Specialty Formulas**\n- **Kendamil**: Offers a smaller range of products, including Classic, Organic, Goat Milk, and Comfort formulas.',
 'Research and Development**\n- **Kendamil**: Focuses on traditional methods and natural ingredients, with a smaller-scale, family-run production model in the UK [Kendamil Blog](https://kendamil.com/blogs/blog/kendamil-vs-aptamil-which-follow-on-formula-is-right-for-your-baby).',
 '*   **Hydrolyzed Formulas (Hypoallergenic):** For babies with milk protein allergies or significant digestive issues, hydrolyzed formulas have proteins broken down into smaller pieces, making them less likely to cause allergic reactions.',
 '*   **Extensively Hydrolyzed Formulas:** These are considered truly hypoallergenic and are for babies with severe allergies to milk protein, as the proteins are broken into very small fragments.',
 '**Hydrolyzed Formulas (Extensively or Partially):**\n    *   In these formulas, proteins are broken down into smaller pieces, making them easier to digest and less likely to cause allergic reactions.',
 '*   **Hydrolyzed Formulas (Partially or Extensively):** Also known as "gentle" or "hypoallergenic" formulas, these have proteins that are broken down into smaller pieces, making them easier to digest and less likely to cause allergic reactions.',
 'In these formulas, the proteins are broken down into smaller pieces, making them less likely to trigger an allergic reaction.',
 '*   **Hypoallergenic (Extensively Hydrolyzed):** Designed for babies with milk protein allergies or sensitivities, where the proteins are broken down into smaller, easier-to-digest particles.',
 "Protein Type:**\n*   **Partially Hydrolyzed Proteins:** In these formulas, the cow's milk proteins are partially broken down into smaller pieces, making them easier for a baby to digest.",
 "*   **Extensively Hydrolyzed Proteins:** For babies with more significant sensitivities or suspected cow's milk protein allergy, extensively hydrolyzed formulas break down proteins into even smaller components.",
 "Gentle/Partially Hydrolyzed Formulas**\nThese formulas contain cow's milk proteins that have been partially broken down (hydrolyzed) into smaller fragments, making them easier to digest.",
 "Extensively Hydrolyzed Protein Formulas (Hypoallergenic)**\nFor babies with a suspected or confirmed cow's milk protein allergy, extensively hydrolyzed formulas break down proteins into very small pieces to minimize allergic reactions.",
 "The proteins in goat milk form a smaller, softer curd in the stomach compared to cow's milk, which may make it easier to digest for some infants.",
 'The proteins in these formulas are extensively hydrolyzed, meaning they are broken down into very small pieces that are less likely to trigger an allergic reaction.',
 'The protein in goat milk is believed to produce smaller, softer curds, which may be gentler on sensitive stomachs.',
 'This process makes the protein molecules smaller, mimicking the size of proteins in breast milk, which can be easier for an immature digestive system to process.',
 "*   **Extensively Hydrolyzed Proteins:** For more significant sensitivities or suspected cow's milk protein allergy, extensively hydrolyzed formulas have proteins broken down into much smaller pieces, reducing the likelihood of an allergic reaction.",
 "Hydrolyzed proteins are cow's milk proteins that have been broken down into smaller pieces, making them easier for a baby's immature digestive system to process and reducing the likelihood of an allergic reaction.",
 "**Partially Hydrolyzed Formulas**\n    These formulas contain cow's milk proteins that have been partially broken down into smaller pieces, making them easier to digest.",
 'Key components and types of formulas include:\n\n*   **Hydrolyzed Proteins:** These formulas contain proteins that have been broken down (hydrolyzed) into smaller, more digestible pieces.',
 '**Holle Goat Milk Formula**  \n   - Goat milk formulas are often easier to digest due to smaller fat globules.',
 '**Bubs Goat Milk Formula**  \n   - A goat milk-based formula that is easier to digest due to smaller fat globules.',
 '**Holle Goat Milk Formula**  \n   - Made with goat milk, which has smaller fat globules for easier digestion.',
 "*   **Partially Hydrolyzed Formulas:** These formulas have cow's milk proteins broken down into smaller pieces, making them easier to digest.",
 "*   **Goat Milk-Based Formulas:** Goat milk naturally contains A2 beta-casein protein, which is smaller and easier to digest than the proteins in cow's milk.",
 'Its fat particles are also smaller, forming a softer curd in the stomach, which can lead to less spitting up and discomfort.',
 "Specialized Formulas (Consult a Pediatrician)**\nIf a baby has specific medical needs, such as a diagnosed allergy or condition, a pediatrician might recommend specialized formulas:\n\n*   **Extensively Hydrolyzed Formulas:** For babies with a confirmed cow's milk protein allergy, these formulas have proteins broken down into very small pieces to reduce allergic reactions.",
 "Gentle/Partially Hydrolyzed Formulas\n\n*   **Description:** These formulas contain cow's milk proteins that have been partially broken down (hydrolyzed) into smaller pieces.",
 'They come in different forms based on the extent of protein breakdown:\n\n*   **Extensively Hydrolyzed Formulas:** The milk proteins are extensively broken down into very small fragments, making them less likely to cause an allergic reaction.',
 '*   **Amino Acid-Based Formulas:** In these formulas, proteins are completely broken down into individual amino acids, the smallest building blocks of protein.',
 'Lifestyle adjustments like positional changes and smaller, more frequent feeds are often the first recommendations.',
 "*   **Protein Sources:** Protein in infant formula can be full-sized (like cow's milk or soy-based) or partially hydrolyzed (broken down into smaller proteins, closer to those in breast milk).",
 '*   **Hydrolyzed Formulas (Partially or Extensively):** In these formulas, proteins are broken down into smaller pieces, making them easier to digest and less likely to cause allergic reactions.',
 '*   **Extensively Hydrolyzed Formulas (Hypoallergenic):** These formulas have proteins broken down into smaller pieces, making them easier to digest and less likely to cause allergic reactions.',
 'These formulas often feature partially hydrolyzed proteins, meaning the milk proteins are broken down into smaller pieces for easier digestion, and may have reduced lactose.',
 '**Alternative Options:**\n\n*   **Goat Milk-Based Formulas (e.g., Kendamil Goat Milk Formula, Aussie Bubs Goat Milk Formula):** Goat milk formulas are often considered easier to digest due to smaller fat particles and a softer curd formation in the stomach, potentially leading to less spitting up.',
 '*   **Iron (in sensitive infants)**: While generally, the iron content in infant formula is not considered a primary cause of constipation, some sources indicate that it can contribute to firmer stools in a small number of particularly sensitive infants.',
 'Formulas with partially hydrolyzed proteins, where the proteins are broken down into smaller, more easily digestible pieces, are often recommended for babies experiencing constipation.',
 'Heavy metals are naturally present in the environment, including soil, water, and food, so small amounts can make their way into a wide range of products.',
 'Even small amounts can have profound neurological impacts, leading to lower IQ, attention deficit disorder, hyperactivity, and behavioral problems.',
 'These substances can pose significant health risks to infants due to their developing organ systems and smaller body sizes.',
 'While small amounts of these metals are often unavoidable, chronic exposure to higher levels can pose health risks, particularly for infants and young children, whose developing brains and bodies are more vulnerable.',
 '*   **Hypoallergenic Formulas (Extensively Hydrolyzed or Amino Acid-Based):** These formulas have proteins broken down into smaller pieces, making them easier to digest and less likely to cause allergic reactions in babies with severe milk protein allergies.',
 "*   **For Sensitivity and Digestive Issues:**\n    *   **Partially Hydrolyzed Formulas (Gentle/Comfort Formulas):** These formulas have cow's milk proteins (whey and casein) broken into smaller pieces, making them easier to digest and potentially reducing discomfort from gas, fussiness, and crying.",
 "*   **For Allergies:**\n    *   **Extensively Hydrolyzed Formulas:** For babies with a diagnosed cow's milk protein allergy (CMPA), these formulas have milk proteins broken down into very small pieces, making them much less likely to cause an allergic reaction.",
 '*   **Extensively Hydrolyzed Formula:** In these formulas, the proteins are broken down into smaller pieces, making them easier to digest for babies with protein sensitivities or allergies.',
 '*   **Extensively Hydrolyzed Formulas:** For babies with diagnosed milk protein allergies or significant digestive problems, these formulas have proteins broken down into very small pieces, making allergic reactions less likely.',
 '*   **Hydrolyzed Formulas:** These formulas have proteins that are broken down into smaller pieces.',
 "*   **Partially Hydrolyzed Formulas:** These break down cow's milk proteins into smaller fragments, making them easier to digest and potentially reducing discomfort like gas and fussiness.",
 "*   **Extensively Hydrolyzed Formulas:** These break cow's milk proteins into very small peptides and are designed for infants with cow's milk protein allergies (CMPA) or severe digestive issues.",
 "*   **Partially Hydrolyzed Formula (Gentle/Comfort Formulas):** In these formulas, cow's milk proteins are broken down into smaller pieces, making them easier to digest and potentially reducing discomfort like gas, fussiness, and crying.",
 "*   **Extensively Hydrolyzed Formula (Hypoallergenic Formulas):** Designed for infants with a cow's milk protein allergy, these formulas have proteins broken down into very small pieces to virtually eliminate allergic reactions.",
 "*   **Partially Hydrolyzed Formulas (Gentle/Sensitive):** In these formulas, cow's milk proteins are broken into smaller pieces, making them easier to digest and potentially reducing discomfort like gas and fussiness.",
 "*   **Extensively Hydrolyzed Formulas (Hypoallergenic):** For babies diagnosed with a cow's milk protein allergy (CMPA), these formulas have proteins broken down into very small pieces, significantly reducing the likelihood of an allergic reaction.",
 '*   **Hydrolyzed Formulas:** In these formulas, the milk proteins are broken down into smaller pieces, making them easier to digest and less likely to cause an allergic reaction.',
 '*   **Extensively Hydrolyzed Formulas:** These formulas have proteins broken down into very small pieces, making them hypoallergenic.',
 "*   **Partially Hydrolyzed Formulas (Gentle Formulas):** In these formulas, cow's milk proteins are broken down into smaller pieces, making them easier to digest and potentially reducing discomfort like gas, fussiness, and crying.",
 '*   **Extensively Hydrolyzed Formulas (Hypoallergenic Formulas):** The milk proteins in these formulas are broken down into very small pieces, significantly reducing the chance of an allergic reaction.',
 '- **Hydrolyzed Formula**: Proteins are broken down into smaller pieces, making it easier to digest.',
 '- **Hydrolyzed Formula**: Proteins in these formulas are broken down into smaller pieces, making them easier to digest.',
 '- **Hydrolyzed Formula**: These formulas contain proteins that are broken down into smaller pieces, making them easier to digest.',
 '- **Hydrolyzed Formula**: Proteins are broken down into smaller pieces, making it easier for babies with allergies or digestive issues to tolerate.',
 '- **Hydrolyzed Formula**: Proteins are broken down into smaller pieces to make digestion easier.',
 '- **Hydrolyzed Formula**: Proteins are broken down into smaller pieces for babies with allergies or digestive issues.',
 '- **Hydrolyzed Formula**: These formulas contain proteins that are broken down into smaller pieces, making them easier to digest.',
 '- **Hydrolyzed Formula**: Proteins are broken down into smaller parts, making it easier for babies with allergies or digestive issues to tolerate.',
 "Key features to look for in formulas for sensitive stomachs include:\n*   **Partially Hydrolyzed Protein** These formulas contain proteins that are already broken down into smaller pieces, making them easier for a baby's digestive system to process.",
 'Hydrolyzed formulas contain proteins that are already broken down into smaller fragments, making them easier for an immature digestive system to process.',
 'The proteins are extensively hydrolyzed, meaning they are broken into smaller pieces to be less allergenic and easier to digest.',
 'They often feature:\n    *   **Hydrolyzed Proteins:** The proteins are broken down into smaller pieces, making them easier to digest for immature digestive systems.',
 "Formulas for sensitive stomachs generally fall into a few categories:\n\n### Partially Hydrolyzed Formulas\nThese formulas contain cow's milk proteins that have been partially broken down into smaller pieces, making them easier for some babies to digest.",
 "*   **Extensively Hydrolyzed Formulas:** These are considered hypoallergenic and are suitable for infants with diagnosed cow's milk protein allergy (CMPA) or severe sensitivities, as the proteins are broken into very small pieces.",
 '*   **For Colic, Gas, and Fussiness (Gentle/Comfort Formulas)**: These formulas often feature partially hydrolyzed proteins (proteins broken down into smaller pieces for easier digestion) and sometimes reduced lactose content.',
 "*   **For Cow's Milk Protein Sensitivity or Allergy (Hydrolyzed and Extensively Hydrolyzed Formulas)**: If a cow's milk protein allergy is suspected, extensively hydrolyzed formulas (where proteins are broken down into very small pieces) or amino acid-based formulas may be necessary.",
 'Formulas designed for sensitive stomachs often feature:\n*   **Partially Hydrolyzed Proteins:** These formulas contain proteins that are already broken down into smaller pieces, making them easier to digest.',
 'These formulas have extensively hydrolyzed proteins, meaning the milk proteins are broken down into very small fragments to minimize allergic reactions.',
 'Hydrolyzed proteins are broken down into smaller pieces, making them easier to digest.',
 '**Key Ingredients to Look For:**\n\n*   **Hydrolyzed Proteins:** These proteins are pre-digested, meaning they are broken down into smaller pieces, which can significantly reduce gas and bloating.',
 "Partially Hydrolyzed Formulas (Gentle Formulas)**\nThese formulas contain cow's milk proteins that have been partially broken down into smaller pieces, making them easier for a baby's developing digestive system to handle.",
 '**Bubs Goat Milk Formula**  \n   - Made with goat milk, which has smaller fat globules and is easier to digest.',
 '**Holle Goat Milk Formula**  \n   - Goat milk formulas are often gentler on sensitive stomachs due to their smaller fat globules and different protein structure.',
 '**Holle Goat Milk Formula**  \n   - Goat milk formulas are often gentler on sensitive stomachs due to their smaller fat globules and different protein structure.',
 'These "sensitive" formulas typically have less lactose than regular cow\'s milk-based formulas and may contain partially hydrolyzed proteins, which are proteins broken down into smaller pieces for easier digestion.',
 "These formulas often feature partially hydrolyzed proteins, meaning the proteins are broken down into smaller pieces to make them easier for a baby's immature digestive system to process.",
 "This means the proteins are broken down into smaller pieces, making them easier for a baby's digestive system to handle.",
 "These formulas typically feature partially hydrolyzed proteins, which are broken down into smaller pieces to be easier for a baby's digestive system to handle.",
 'When choosing a gentle formula, it\'s important to understand that "gentle" often refers to formulas with partially hydrolyzed proteins, meaning the milk proteins are broken down into smaller pieces to make them easier to digest.',
 'Key characteristics and ingredients to look for in gentle formulas include:\n*   **Partially Hydrolyzed Proteins** These are milk proteins that have been broken down into smaller pieces, making them easier to digest than the larger, intact proteins found in standard formulas.',
 'Here are some of the top gentle formula options and their distinguishing features:\n\n**Key Characteristics of Gentle Formulas:**\n\n*   **Partially Hydrolyzed Protein:** Many gentle formulas contain partially hydrolyzed whey protein, meaning the proteins are broken down into smaller pieces, making them easier for a baby to digest.',
 "Top recommendations include:\n*   **Bobbie Organic Gentle Infant Formula**\n*   **HiPP Comfort Formula**\n*   **HiPP HA Formula**\n*   **Kendamil Goat Milk Formula**\n*   **Earth's Best Organic Gentle Formula**\n*   **Similac Pro Total Comfort**\n*   **Enfamil Gentlease**\n*   **Baby's Only A2 Organic Milk Infant Formula**\n*   **Enfamil Reguline**\n*   **Gerber GoodStart GentlePro**\n*   **Gerber GoodStart SoothePro**\n\nThese formulas often contain proteins broken down into smaller pieces to aid digestion.",
 'These formulas have milk proteins broken down into very small pieces, making them less likely to trigger an allergic reaction and are typically lactose-free.',
 "Extensively hydrolyzed formulas are particularly recommended if a cow's milk protein allergy is suspected, as they break proteins into very small pieces that are less likely to trigger an allergic reaction.",
 "Formulas designed to alleviate colic and gas often feature specific characteristics:\n\n*   **Hydrolyzed Proteins** These formulas contain proteins that have been broken down into smaller pieces, making them easier for a baby's immature digestive system to process.",
 'Formulas designed for colic and gas often feature:\n*   **Hydrolyzed Proteins:** These formulas contain proteins that have been broken down into smaller pieces, making them easier to digest.',
 'Formulas designed to help with colic and gas often feature specific characteristics:\n\n*   **Partially Hydrolyzed Protein Formulas** These "gentle" or "comfort" formulas contain cow\'s milk proteins that have been partially broken down into smaller pieces, making them easier for a baby\'s immature digestive system to process.',
 "Formulas designed for colic and gas often feature:\n\n*   **Hydrolyzed Proteins:** These proteins are broken down into smaller pieces, making them easier for a baby's immature digestive system to process.",
 'Formulas commonly recommended for babies experiencing colic and gas often fall into several categories:\n\n*   **Partially Hydrolyzed or "Gentle" Formulas** These formulas contain cow\'s milk proteins that have been partially broken down into smaller pieces, making them easier for a baby\'s developing digestive system to process.',
 "*   **Extensively Hydrolyzed or Hypoallergenic Formulas** For babies with suspected cow's milk protein allergy (CMPA), these formulas have proteins broken down into very small components to minimize allergic reactions.",

In [58]:
{c: list(dict.fromkeys(snips))[:8] for c, snips in comp_snippets.items()}

{'SMA': ['**Brain and Immune Development**: Aptamil links immune system support with cognitive development, promoting the idea of "stronger immunity, smarter future" through its advanced nutritional engineering [RSIS International](https://rsisinternational.org/journals/ijriss/uploads/vol10-iss21-pg1255-1269-202608_pdf.pdf).',
  'Specialty Formulas**\n- **Kendamil**: Offers a smaller range of products, including Classic, Organic, Goat Milk, and Comfort formulas.',
  'Research and Development**\n- **Kendamil**: Focuses on traditional methods and natural ingredients, with a smaller-scale, family-run production model in the UK [Kendamil Blog](https://kendamil.com/blogs/blog/kendamil-vs-aptamil-which-follow-on-formula-is-right-for-your-baby).',
  '*   **Hydrolyzed Formulas (Hypoallergenic):** For babies with milk protein allergies or significant digestive issues, hydrolyzed formulas have proteins broken down into smaller pieces, making them less likely to cause allergic reactions.',
  '*   **Extensively Hydrolyzed Formulas:** These are considered truly hypoallergenic and are for babies with severe allergies to milk protein, as the proteins are broken into very small fragments.',
  '**Hydrolyzed Formulas (Extensively or Partially):**\n    *   In these formulas, proteins are broken down into smaller pieces, making them easier to digest and less likely to cause allergic reactions.',
  '*   **Hydrolyzed Formulas (Partially or Extensively):** Also known as "gentle" or "hypoallergenic" formulas, these have proteins that are broken down into smaller pieces, making them easier to digest and less likely to cause allergic reactions.',
  'In these formulas, the proteins are broken down into smaller pieces, making them less likely to trigger an allergic reaction.'],
 'Enfamil': ['Aptamil and Enfamil are two prominent infant formula brands, both formulated to support infant immunity and cognitive development, though they emphasize slightly different approaches and ingredient blends.',
  '**For Cognitive Development:**\nBoth Aptamil and Enfamil incorporate Docosahexaenoic Acid (DHA) and Arachidonic Acid (ARA), which are essential omega-3 and omega-6 fatty acids crucial for the development of the brain, eyes, and nervous system.',
  'Enfamil, particularly its NeuroPro line, places a strong emphasis on cognitive development.',
  "Enfamil states that its NeuroPro formula's advanced formulation, including MFGM and DHA, supports brain development similar to that of breastfed babies.",
  'Some comparisons suggest that while Enfamil is particularly innovative in cognitive development, Aptamil Gold also offers strong DHA support.',
  'Enfamil also contains prebiotics to enhance the immune system by nurturing beneficial bacteria in the digestive tract.',
  'Enfamil NeuroPro features a blend of polydextrose (PDX) and GOS prebiotics, along with a HuMO6 immune blend, designed to support the immune system.',
  'Enfamil Premium is specifically designed for infants with immature immune systems, such as newborns up to three months old.']}